### ISSUE TITLE
[翻訳フィードバック] Lispの思想

### ISSUE THREAD

**Issue by g000001** [postdcc/feedback#10]
いつもはある原文ソースへのリンクがありませんが、記載漏れでしょうか
原文はこちら?
https://dev.to/ericnormand/the-idea-of-lisp

原文では"アイデア"ですが、所々"思想"としてしまったのは何故なのでしょうか。  
この文章では、Lispの根底に流れる統一された思想のようなものは解説されておらず、紹介するにあたいする個別の素晴しい(当時としては画期的だった)アイデアが羅列されているのみです。  
(Lispといえば、思想、悟り、というように無駄に深淵なものという先入観を与えるのに私は反対です。)

この文章の源となったと思われるアラン・ケイの引用の中でもアイデアですが、思想としてしまったために最後の締めも空振りになっています。

**Comment by remore** [comment]
的確なフィードバックありがとうございます。

> いつもはある原文ソースへのリンクがありませんが、記載漏れでしょうか

記載漏れでしたので、記載させて頂きました。

> 原文では"アイデア"ですが、所々"思想"としてしまったのは何故なのでしょうか。
> この文章では、Lispの根底に流れる統一された思想のようなものは解説されておらず、紹介するにあたいする個別の素晴しい(当時としては画期的だった)アイデアが羅列されているのみです。
> (Lispといえば、思想、悟り、というように無駄に深淵なものという先入観を与えるのに私は反対です。)

できるだけ原文に忠実に訳したいと考えているのですが、原文に即しておりませんでしたら申し訳ありません。一部の `Idea` を `思想` としているのは、日本語文としての読みやすさを確保するためでした。

例えば以下の文章ですが、

> Lispの思想の一体どこに、オブジェクト指向プログラミングの作成者たちはそんなにも魅了されるのでしょうか。
> そしてまた、思想となっているプログラミング言語というものは、どうやったら説明できるでしょうか。

これをアイデアとして日本語表記すると

> Lispのアイデアの一体どこに、オブジェクト指向プログラミングの作成者たちはそんなにも魅了されるのでしょうか。
> そしてまた、アイデアとなっているプログラミング言語というものは、どうやったら説明できるでしょうか。

ということになりますが、「アイデアとなっているプログラミング言語」という表記が原文の意図を忠実に再現できているように感じられませんでした。（私の国語力が低いという問題だったら申し訳ないのですが、「アイデアとなっているプログラミング言語」という言葉が最後まで腑に落ちませんでした）

この「思想」という言葉を使った部分は、最後まで表記上悩んだ部分でしたので、ご指摘頂いているポイントはその通りの懸念があると思います。今回の翻訳はそういった先入観を導入することを助長したい意図のものではありませんので、もし上記例を初めとした訳語を「アイデア」とした場合の訳文の読みづらさを解決できる修正があればぜひ導入させて頂きたいのですが、今のところ考えついていないという状況です。

この内容がお問い合わせ頂いた事への回答になっているか分かりませんが、ひとまずの説明として回答させて頂きます。

**Comment by g000001** [comment]
この文章でのideaは、「発明(invention)」でも意味は通るかなと思います。
しかし発明では大袈裟なので ideaとしたのではないでしょうか。
そうなると「着想・着眼点・発想」位になると思います。
(個人の解釈ですので、原著者がinventionに置き換えても意味は通るとするかは分かりませんのでご確認下さい)

思想はコミュニティによって醸成されることもありますし、移ろいゆくこともあり、もやもやしたものですが、発明・発想は発明者に帰属しますし、変遷することもなく、もやっとしたものはありません。
この文章で解説されているアイデアにも、もやっとした所はないと思います。

思想には単に「考え」という意味もあるようです。しかし、近年では、多分にthought、philosophyのようなものを含んでいると思います。
「Lispの思想」とすると、「Lispの価値観」、「Lispの哲学」みたいなものに思えてしまいます。


以下、発明・発想でも良いと思いますが、アイデアに統一して考察してみました。
発明・発想という意味でのアイデアであれば特に意味が通らないことは無さそうに思えました。
ぶれがあるところは、「LISPの発想・アイデア」とでも補えば良さそうに思えます。

> Lispのアイデアの一体どこに、オブジェクト指向プログラミングの作成者たちはそんなにも魅了されるのでしょうか。
何故、オブジェクト指向プログラミングの作成者たちは、そんなにもLispのアイデアに魅了されるのでしょうか。

> そしてまた、思想となっているプログラミング言語というものは、どうやったら説明できるでしょうか
そしてまた、アイデアとされるプログラミング言語というものは、どうやったら説明できるでしょうか

> Fortranは大きな成果でしたが、Lispは大きな思想だったと言えるでしょう。
Fortranは大きな成果でしたが、Lispは大きなアイデアだったと言えるでしょう。

> Lispの思想から直接導き出されるLispのいくつかの機能です。
Lispのアイデアから直接導き出されるLispのいくつかの機能です。 

> しかしLispという思想は生き残ります。現時点で最も有望な、その生まれ変わりはJVMとJavaScriptで動作するClojureです。
しかしLispというアイデアは生き残ります。現時点で最も有望な、その生まれ変わりはJVMとJavaScriptで動作するClojureです。

> コンピュータ科学、プログラミングの歴史、あるいはLispの重要な思想に興味があるなら、ぜひPurelyFunctional.tv Newsletterをチェックしてみてください。
コンピュータ科学、プログラミングの歴史、あるいはLispのアイデアの数々に興味があるなら、ぜひPurelyFunctional.tv Newsletterをチェックしてみてください。

**Comment by remore** [comment]
丁寧に解説と提案をいただきありがとうございます。全面的に頂いたご提案の内容の方がより正確な表現になっていると思われます。

> そしてまた、アイデアとなっているプログラミング言語というものは、どうやったら説明できるでしょうか

では不自然に思われていましたが、

> そしてまた、アイデアとされるプログラミング言語というものは、どうやったら説明できるでしょうか

この訳では意味を理解できるように思え、この部分についても言い回しや私の和訳能力の問題で精度が低い訳となっておりました。初版で適切な言葉を選択できておらず、申し訳ありませんでした。

頂いた修正案含めて「思想」という言葉と除去して更新いたしました。ご確認頂けますと幸いです。

**Comment by g000001** [comment]
お手数をおかけいたしました。ご検討頂きありがとうございます。
面白い記事の翻訳ありがとうございます🙇
これからもpost.ccさんの記事を楽しみにしております。
