### ISSUE TITLE
[翻訳フィードバック] プログラマの採用面接で聞かれる、データ構造とアルゴリズムに関する50以上の質問

### ISSUE THREAD

**Issue by koichiasakura** [postdcc/feedback#100]
いつも興味深い記事の翻訳ありがとうございます．

### 記事タイトル or URL

https://postd.cc/50-data-structure-and-algorithms-interview-questions-for-programmers/

### フィードバック内容

"How do you …" などの質問の日本語訳で， ”How” が「どのように、…」と訳されているのが気になりました．意訳になるかも知れませんが「〜するにはどうすればよいですか？」という訳の方がわかりやすいと思います．

例えば，一番最初の質問

>  How do you find the missing number in a given integer array of 1 to 100?

であれば，

「どのように、1から100までの与えられた整数の配列の中から足りない数字を探しますか？」

ではなく，

「1から100までの与えられた整数の配列の中から足りない数字を探すにはどうすればよいですか？」

の方がわかりやすいのではないかと思います．

**Comment by munehiroochi** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を確認して、質問の翻訳を見直しました。
今後ともPOSTDをよろしくお願いいたします。
