### ISSUE TITLE
[翻訳フィードバック] 役立つコードレビュー　8つのヒント

### ISSUE THREAD

**Issue by ytakahashi** [postdcc/feedback#101]
### 記事タイトル or URL

https://postd.cc/8-tips-for-great-code-reviews/

### フィードバック内容

4.読みやすさを心がける に

> コードブロックに三連バッククォート（“`）を使ったりすると、上手に考えを伝えることができます。

とありますが、三連バッククートが ``` でなく "` となっています。

**Comment by munehiroochi** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を確認して修正しました。
今後ともPOSTDをよろしくお願いいたします。
