### ISSUE TITLE
[翻訳フィードバック] 分散システムについて語るときに我々の語ること ― 分散システムにまつわる重要な概念について

### ISSUE THREAD

**Issue by dora-gt** [postdcc/feedback#102]
### 記事タイトル or URL
https://postd.cc/learning-about-distributed-systems/

### フィードバック内容
とても参考になりました。ありがとうございました。

**Comment by munehiroochi** [comment]
フィードバックありがとうございます。
今後ともPOSTDをよろしくお願いいたします。
