### ISSUE TITLE
[翻訳フィードバック] JavaScriptにおける継承のパターン4種類の概要と対比

### ISSUE THREAD

**Issue by magai** [postdcc/feedback#103]
### 記事タイトル or URL
https://postd.cc/javascript-inheritance-patterns/

### フィードバック内容
> This method really displays the prototypal inheritance behind the workings of the class syntax

が、

> このメソッドでは、classシンタックスの後に、プロトタイプ継承を実際に表示することができます。

と訳されているのはちょっと違う感じがします。このメソッドではclass構文の働きの背後にあるプロトタイプ継承が見えます、的な感じの意味だと思うので。

**Comment by munehiroochi** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を汲み取って修正しました。
今後ともPOSTDをよろしくお願いいたします。
