### ISSUE TITLE
[翻訳フィードバック] 週末にいちばん多く使われるプログラミング言語は？

### ISSUE THREAD

**Issue by momohatt** [postdcc/feedback#104]
### 記事タイトル or URL
[週末にいちばん多く使われるプログラミング言語は？](https://postd.cc/what-programming-languages-weekends/)

### フィードバック内容
記事中の画像がリンク切れして見られなくなっているようです。
お手数ですが修正をお願いいたします。

**Comment by takesako** [comment]
フィードバックありがとうございます。
おっしゃる通り画像のリンク切れが発生しておりました。
ご指摘の頂いた内容を元に修正しました。
今後ともPOSTDをよろしくお願いいたします。

**Comment by momohatt** [comment]
ありがとうございました！
