### ISSUE TITLE
[翻訳フィードバック] なぜPythonはこんなにも遅いのか？

### ISSUE THREAD

**Issue by ghost** [postdcc/feedback#105]
### 記事タイトル or URL
[なぜPythonはこんなにも遅いのか？](https://postd.cc/why-is-python-so-slow/)

### フィードバック内容
最初の引用ブロック内の翻訳を以下のように訳したほうが適切かと思いますがいかがでしょうか:
- 該当部: ベンチマークがないのが一番ですが,
- 修正案: 完璧なベンチマークはありませんが,
- 原文: No benchmark is perfect,

**Comment by takesako** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を汲み取って翻訳を修正しました。
今後ともPOSTDをよろしくお願いいたします。
