### ISSUE TITLE
[翻訳フィードバック] 2016年、C言語はどう書くべきか (後編)

### ISSUE THREAD

**Issue by uraran** [postdcc/feedback#106]
### 記事タイトル or URL

https://postd.cc/how-to-c-in-2016-2/

### フィードバック内容

最後の「出典」内

> Christoperから、-02対-03の項が明確ではないと指摘あり。

は
「…-O2対-O3…」(ゼロではなくオー)
の誤記と思われます。

**Comment by takesako** [comment]
フィードバックありがとうございます。
おっしゃる通り、最適化オプションの誤記でした。
ご指摘の頂いた内容を元に誤記を修正しました。
今後ともPOSTDをよろしくお願いいたします。
