### ISSUE TITLE
[翻訳フィードバック] PHPはもうダメだ、PHP万歳！

### ISSUE THREAD

**Issue by smori1983** [postdcc/feedback#107]
### 記事タイトル or URL

https://postd.cc/php-is-dead-viva-le-php/

### フィードバック内容

> ReactやVue、Abgularのような最新のフロントエンドのフレームワークとうまく適合するAPIを構築するのにPHPは優れた言語です。

綴りミスを見つけました。

誤）Abgular
正）Angular

よろしくお願いいたします。

**Comment by takesako** [comment]
フィードバックありがとうございます。
ご指摘の頂いた綴りミスを修正しました。
今後ともPOSTDをよろしくお願いいたします。
