### ISSUE TITLE
[翻訳フィードバック] RustにおけるfutureとgRPC

### ISSUE THREAD

**Issue by ksato9700** [postdcc/feedback#108]
### 記事タイトル or URL
[RustにおけるfutureとgRPC](https://postd.cc/futuresandgrpc/)
### フィードバック内容
一番下の「github.com/pingcap/grpc-rs」というリンクがおそらく https://github.com/pingcap/grpc-rs を意図しているのだと思うのですが、相対URL指定になっているので、https://postd.cc/futuresandgrpc/github.com/pingcap/grpc-rs を指していて404になってしまっています。

**Comment by takesako** [comment]
フィードバックありがとうございます。
ご指摘の頂いた通りリンク切れが発生しておりました。
リンク先のURLを修正しました。
今後ともPOSTDをよろしくお願いいたします。
