### ISSUE TITLE
[翻訳フィードバック] オーバーエンジニアリングの正体とその向き合い方

### ISSUE THREAD

**Issue by h-matsuo** [postdcc/feedback#109]
### 記事タイトル or URL

[オーバーエンジニアリングの正体とその向き合い方](https://postd.cc/how-to-accept-over-engineering-for-what-it-really-is/)

### フィードバック内容

翻訳内容についてのフィードバックではないのですが、記事中に埋め込まれている JSFiddle のリソースが HTTP で指定されているため、Mixed Content エラーによりコードが表示されていません。

**Comment by takesako** [comment]
フィードバックありがとうございます。
ご指摘の頂いた通り、正しくインラインコンテンツが
表示されていませんでしたのでURLをhttpsに修正しました。
今後ともPOSTDをよろしくお願いいたします。
