### ISSUE TITLE
[翻訳フィードバック] 開発者が知っておくべきSOLIDの原則

### ISSUE THREAD

**Issue by besaklish** [postdcc/feedback#110]
### 記事タイトル or URL
https://postd.cc/solid-principles-every-developer-should-know/

### フィードバック内容
以下の部分の訳が間違っていると思います。
「リスコフの置換原則
サブクラスは、そのスーパークラスで代用可能でなければならない」

私が思う正しい訳は
「リスコフの置換原則
スーパークラスは、そのサブクラスで代用可能でなければならない」
です。

POSTD様の訳だと文脈に沿わないとも感じます。

**Comment by takesako** [comment]
フィードバックありがとうございます。
おっしゃる通り誤訳が発生していたと思います。
ご指摘の頂いた内容を汲み取って翻訳を修正しました。
今後ともPOSTDをよろしくお願いいたします。
