### ISSUE TITLE
[翻訳フィードバック] 勾配降下法の最適化アルゴリズムを概観する

### ISSUE THREAD

**Issue by masathehero** [postdcc/feedback#111]
### 記事タイトル or URL
- タイトル: 勾配降下法の最適化アルゴリズムを概観する
- URL: https://postd.cc/optimizing-gradient-descent/
### フィードバック内容
数式が正常に表示されていません。

**Comment by takesako** [comment]
フィードバックありがとうございます。
おっしゃる通り数式が正しく表示されておりませんでした。
ご指摘の頂いた内容を元に修正しました。
今後ともPOSTDをよろしくお願いいたします。
