### ISSUE TITLE
[翻訳フィードバック] H.264の秘密

### ISSUE THREAD

**Issue by shutosg** [postdcc/feedback#112]
### 記事タイトル or URL
https://postd.cc/h-264-is-magic/

### フィードバック内容
> ここまでが、サイズを落とす方法の説明でした。可逆圧縮におけるこの処理のことを量子化と呼びます。

とありますが、原文は

> This process in lossy compression is ...

なので

> 非可逆圧縮

の誤訳です。

**Comment by takesako** [comment]
フィードバックありがとうございます。
おっしゃる通りだと思います。
ご指摘の頂いた内容を元に誤訳を修正しました。
今後ともPOSTDをよろしくお願いいたします。
