### ISSUE TITLE
[翻訳フィードバック] 若手開発者の後悔

### ISSUE THREAD

**Issue by kynefuk** [postdcc/feedback#113]
### 記事タイトル or URL
[若手開発者の公開](https://postd.cc/the-sorrows-of-young-developer/)

### フィードバック内容
いくつか日本語表記の誤り、または不自然な表現がありましたので
修正案を出しました。お手すきの際にご確認いただけますと幸いです。

> しかし、ここでの最初プロジェクトは結果的に問題だらけに終わりました。

→しかし、ここでの最初**の**プロジェクトは結果的に問題だらけに終わりました。

> この若手開発者は、機能は絶対に変わらないものだと思っていた。

→この若手開発者は、機能は絶対に変わらないものだと思ってい**ました**。

> 全てのコードを高速で、コンフィギュレーションが可能で、ロバスト性のあるものにしたかったで

→全てのコードを高速で、コンフィギュレーションが可能で、ロバスト性のあるものにしたかった**の**で、

**Comment by takesako** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を汲み取って翻訳を修正しました。
今後ともPOSTDをよろしくお願いいたします。
