### ISSUE TITLE
[翻訳フィードバック] @extendを使うべき時、@mixinを使うべき時

### ISSUE THREAD

**Issue by masmatsum** [postdcc/feedback#114]
### 記事タイトル or URL
https://postd.cc/when-to-use-extend-when-to-use-a-mixin/

#### 1.
(原文: (In fact, this is probably a perfect use-case for an argument-less mixin. We’ll come back to that soon.))
(実際には、このケースでは引数を持たない@mixinが最適です@mixinについてはあとで述べます)
→(実際には、このケースでは引数を持たない@mixinが最適です。@mixinについてはあとで述べます)

文末の句点（マル）が抜けています。

#### 2.
「この結果はご想像の通り、以下のようになります。」のあとのコード例の最初が
```
.alert--error > .alert__text {
    font-weight: bold;
}
```
となっていますが、

正しくは
```
.header--home > .header__tagline,
.btn--warning,
.alert--error > .alert__text {
    font-weight: bold;
}
```
です。原文のコード例を確認してください（原文だと "This, as you would expect, gives us the following:" の直後です）。

#### 3.
(原文: so this repetition is sensible, )
この複製は繊細です。
→この複製は理にかなっています。

sensible は「理にかなっている」などの意味です。
参考： https://www.ldoceonline.com/dictionary/sensible
「繊細」ではありません。

#### 4.
(原文: See it like a Sassy extension of your copy/paste clipboard )
@mixinはクリップボードのコピー＆ペーストのSassy版拡張のようなものだと思ってください。
→@mixinはクリップボードのコピー＆ペーストのSass版拡張のようなものだと思ってください。

"Sassy" は「Sassの」「Sass版」と訳せます。
「Sassy版」だと「頭痛が痛い」みたいで違和感があります。

#### 5.
(原文: a Sassy copy/paste )
Sassyのコピー＆ペースト
→Sass版コピー＆ペースト

上と同じです。

#### 6.
(原文: Use @extend for same-for-a-reason; use a mixin for same-just-because.)
@extendは重複に理由がある時に使いましょう。@mixinは特に理由なく重複させる際に使いましょう。
→@extendは「理由があって同じ」である場合に使いましょう。@mixinは「偶然同じ」の場合に使いましょう。

same を「重複」と訳していますが、「重複」と「同じ」は異なる概念です（同じものが複数個あるときに「重複」と呼ぶ）。
そして、本文の中で「重複」という概念や言葉は、あくまでDRY関連のところで出てくるものです。
この記事の全体の要約でsameを「重複」と訳すと、混乱しやすいと思います。
（手動での）重複を排除するために @mixin を使うという点からも、「重複させる」と訳すのは少しおかしいと感じます。

**Comment by takesako** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を汲み取って翻訳を修正しました。
今後ともPOSTDをよろしくお願いいたします。
