### ISSUE TITLE
[翻訳フィードバック] Vim-Galore : Vimについて知っておくべき全てのこと (1/5)

### ISSUE THREAD

**Issue by rhoboro** [postdcc/feedback#115]
### 記事タイトル or URL

https://postd.cc/vim-galore-1/

### フィードバック内容

良記事ありがとうございます。この記事はよく紹介させていただいているのですが、以前から[ミニマルなvimrc](https://postd.cc/vim-galore-1/#minimal-vimrc)にある2つのリンクが切れております。
原文の方は更新されていましたので、更新していただけると幸いです。
https://github.com/mhinz/vim-galore#minimal-vimrc

**Comment by takesako** [comment]
フィードバックありがとうございます。
おっしゃる通りリンク切れが発生しておりました。
ご指摘の頂いた内容を元に修正しました。
この度は対応が遅くなってしまい申し訳ございませんでした。
今後ともPOSTDをよろしくお願いいたします。
