### ISSUE TITLE
[翻訳フィードバック] すばらしいビット

### ISSUE THREAD

**Issue by yambe2002** [postdcc/feedback#12]
・「n乗ビット」は「n番目のビット」の方がベターと感じました
・『最大値整数（64ビット）の取得』の「64ビット」は原文どおり「long」にすべきと思います
・「JavaScriptよりも35%処速が速くなります。」は「JavaScriptでは~」の誤訳
・「2つの値が同じ記号であることを確認」「記号の反転」の「記号」は「符号」でしょうか
・「2nの計算」と「mの2n剰余」はいずれも「2^n」の誤記でしょうか
・「最右の1ビットを分離(抽出)」と「最右の0ビットを分離(抽出)」は原文が間違えている気がします・・・（質問してみます）
・「最右ビットを0から1に設定」は「最右のビット0を1に設定」で誤訳です
・「Invert letter's case:」「Get letter's position in alphabet (for lowercase letters only):」の訳が抜けています（たぶん訳のあとに原文がアップされたのだと思いますが）

**Comment by yambe2002** [comment]
これは正しそうです。失礼しました
・「最右の1ビットを分離(抽出)」と「最右の0ビットを分離(抽出)」

**Comment by satomi-yako** [comment]
本記事に対するフィードバック、翻訳修正のご提案ありがとうございました。
また、対応および返信が遅くなってしまい大変失礼いたしました。
参考にさせて頂き修正版を公開させて頂きましたので、ご報告させて頂きます。
（原文で追加されておりました部分も追記させて頂いております。）
今後とも、POSTDを何卒よろしくお願いいたします。
