### ISSUE TITLE
[翻訳フィードバック] 勾配降下法の最適化アルゴリズムを概観する

### ISSUE THREAD

**Issue by poemperl** [postdcc/feedback#13]
I grad to read some recent document's contents related to deep learning in Japanese. Your webpage is very easy to look at. Especially, related to Adagrad, I could deepen the understanding of it because I couldn't find any article of it. I have a proposition about deep learning contents you use. Why don't you try to explain "GRID LONG SHORT-TERM MEMORY"? (7 Jan 2016)
  https://arxiv.org/abs/1507.01526

**Comment by mk2** [comment]
Thank you for your feedback. The suggested articles will be examined by us. Thank you POSTD in the future.
