### ISSUE TITLE
[翻訳フィードバック] ハミング符号 : データの誤り検知/訂正をインタラクティブに学ぶ

### ISSUE THREAD

**Issue by koba-e964** [postdcc/feedback#14]
「これにより、ハミング距離は3から4に増加し、アルゴリズムが2つのビットの誤りを正しく検知・訂正できるようになります。」は
「これにより、ハミング距離は3から4に増加し、アルゴリズムが2つのビットの誤りを正しく検知できるようになります。」の方が良いです。(correctly detectなので)

**Comment by re-fort** [comment]
ご指摘ありがとうございます。
確認が遅くなってしまいましたが、上記の通り記述を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします。
