### ISSUE TITLE
[翻訳フィードバック] どれだけ速く文字列からスペースを削除できるのか

### ISSUE THREAD

**Issue by pachicoma** [postdcc/feedback#15]
ジャンプテーブルを使ったコードの途中が抜けています

**Comment by satomi-yako** [comment]
本記事に対するフィードバックありがとうございました。
また、確認や対応などが遅れてしまいまして申し訳ございませんでした。 
確認しましたところ、たしかにコードの途中が抜け落ちておりました。
こちら、修正版を公開させて頂きましたので、ご報告させて頂きます。
今後とも、POSTDを何卒よろしくお願いいたします。
