### ISSUE TITLE
[翻訳フィードバック] どれだけ速く文字列からスペースを削除できるのか

### ISSUE THREAD

**Issue by uehaj** [postdcc/feedback#16]
ベンチ結果の単位「サイクル/毎秒」はおかしい。原文では「サイクル/バイト」になっている。バイト当たりに要するCPUサイクル

**Comment by satomi-yako** [comment]
本記事に対するフィードバックありがとうございました。
また、確認や対応などが遅れてしまいまして申し訳ございませんでした。 
原文と異なる表記をしていることが確認できました。
こちら、修正版を公開させて頂きましたので、ご報告させて頂きます。
今後とも、POSTDを何卒よろしくお願いいたします。
