### ISSUE TITLE
[翻訳フィードバック] 型クラスはインターフェースとどう違うのか

### ISSUE THREAD

**Issue by ssirai** [postdcc/feedback#17]
## 型クラスについての概要/要約

型クラスの定義4について。

> 4. This is the function type definition (or list of such) we need to define for a in order to make a an instance of Ord.

> 4. これはaをOrdのインスタンスにするために、a用に定義する必要のある関数型の定義（あるいはそれに類似するもの）です。

(or list of such)は「あるいはそのような [定義の]リスト」という意味だと思います。インスタンス上で定義されるべき関数は1つ以上あるかもしれないという意味です。

型クラスの定義の解釈の部分。

> Declare a class Ord that is parameterized on some type a where a has an Eq type class instance. 

> Ordクラスを宣言します。これは、aがEq型のインスタンスを持つ場合に、いくつかの型aをパラメータ化します。

someは「なんらかの」を意味しています。 パラメータ化された型aはいくつもあるという言い方はしないはずです。またEq型クラスを省略してEq型というと誤解を招くと思います。

私訳を載せます。

> Eq型クラスのインスタンスを持つ、なんらかの型aでパラメータ化されているOrdクラスを宣言する。

「型クラスについての概要/要約」最終段落。

> 演算子orderingを定義してみましょう。

ordering operatorで検索しても訳語が見つからないので考えどころですが、「順序付け演算子」とでもしておけばよいのではないでしょうか。orderingという演算子がコード中に記載されているわけではないので、英単語そのままで記述するのは不適切です。

## インターフェースと似ているところ

> これらの1つを優先させなければ、メソッドを呼び出そうとする際に無限にループを続けることになります。

> If we don’t override one of them, then we’ll loop infinitely if we try to call a method.

overrideは[オーバーライド](https://ja.wikipedia.org/wiki/%E3%82%AA%E3%83%BC%E3%83%90%E3%83%BC%E3%83%A9%E3%82%A4%E3%83%89)とそのまま訳せばいいと思います。 one of  themは「どちらか[少なくとも]一つ」という意味です。

> Javaと同等のコードはこんな風になります。

日本語の問題ですが「Javaによる同等のコード」とした方が自然ではないでしょうか。

> Java doesn’t handle sum types very well, so we’ll just do Large from our ToyOrd class above.

> Javaはタイプをまとめて処理することが得手ではありませんので、上位のToyOrdクラスからLargeを処理するだけになります。

sum typesで一つの用語です。直和型と訳されるのが一般的です。

## return型ポリモーフィズムへ

> We can write a safe division by zero function:

> ゼロ関数を使って安全な区分が書けます。

safe division by zero functionは「安全なゼロ除算関数」と訳すべきです。

以上、雑多な指摘で失礼しました。名前の記載についてはどちらでも構いません。

**Comment by mk2** [comment]
頂きましたご指摘を確認し、再度翻訳を検討し修正いたしました。

http://postd.cc/how_do_type_classes_differ_from_interfaces/

いただいたご指摘に関しましては、非常に的確なものと感じましたのでほぼほぼ取り入れさせていただきました。大変感謝しております。
今後ともPOSTDをどうぞよろしくお願いいたします。
