### ISSUE TITLE
[翻訳フィードバック] どれだけ速く文字列からスペースを削除できるのか

### ISSUE THREAD

**Issue by kwatch** [postdcc/feedback#19]
> 結局、64ビットのワードを使用しなくても良いのです。

の直後のコードは、原文と違っています。具第的には、`pos += jump_table[ (unsigned char)bytes[pos] ];` と `}` が欠けています。

これはこのコードのキモとなる一行なので、修正していただければと思います。

**Comment by satomi-yako** [comment]
本記事に対するフィードバックありがとうございました。
また、確認や対応などが遅れてしまいまして申し訳ございませんでした。 
確認しましたところ、たしかにコードの途中が抜け落ちておりました。
こちら、修正版を公開させて頂きましたので、ご報告させて頂きます。
今後とも、POSTDを何卒よろしくお願いいたします。
