### ISSUE TITLE
RustとDNSの1年の誤訳

### ISSUE THREAD

**Issue by tamo** [postdcc/feedback#2]
メールが届いていないみたいなので、こちらにも書きますね。以下は、21日と22日に送信したものから罵詈雑言を除いたものです。

「Goは学習するにはとても面白い言語で、私が特に素晴らしいと評価していたJavaに由来する言語です。」
という文で、coming の分詞構文の主語は直後の I だと思います。つまり、
「Goは学習していて楽しい言語で、Java出身の私は特にひとつの点を素晴らしいと評価しました。それはシングルバイナリを……」
というような文です。だってGoはJavaの子孫じゃありませんよね。

「正直言って、Goでプログラムを書くまでは、「C言語にスタティックバイナリがあれば……」と何度思ったか分かりません。」
という文は、not until を「して初めて……」と訳すのが普通です。http://ejje.weblio.jp/content/not+until
「正直言って、Goでプログラムを書いて初めて、C言語のスタティックバイナリ(生成機能)を(自分が)どれほど気に入っていたか気付いたのです。」
って感じでしょうね。だって C にはスタティックバイナリがありますから。

「そのほうがより明確だと考えたからです（上記のコードで分かるように、これは16進数とは対照的です。きれいに整える必要がありますが、壊れないのであれば修正する必要もありません）。」
の、「上記のコードで分かるように」はダメです。
「上記のコードに残っている16進数とは対照的です。そのうち整理しなきゃとは思うのですが、「壊れていないものを直すな」ってやつです」
のような意味だと思います。

「1つ言っておかなければいけないのは、Rustの人間工学にはとても素晴らしいものがある、ということです。例えば、バイナリリテラルのサポートがあります。」
これは文脈と合いません。それまでずっとバイナリリテラルの話をしていたのですから、
「このバイナリリテラルを含め、本当にRustの人間工学には素晴らしいものがあると言わざるを得ません。」
とでもしなければ、別の話かと思ってしまいます。
その後の、途中に _ を入れられるのは Java に比べた優位点です。ですから、
「バイナリリテラルはJavaもちょうど1.7でサポートしたところですが、これも含めてRustの人間工学には素晴らしいものがあると言わざるを得ません。(単に2進数をリテラル表記できることに)加えて、リテラルを _ で区切って見やすくすることができるのも素晴らしいです」
というようなことを言っています。

hexを「16進数」とするように、binaryも「2進数」にしたほうが良さそうな箇所がある気がしましたが、Javaのドキュメントなどでbinary literalが「バイナリリテラル」になっていますから、仕方ないですかね。

「ここ何年かずっとJavaを使っていた理由はここにありました。しかし今では、Javaより安全が保障されるシステムレベルプログラミングに戻ってこられました。」
は、まるで「システムレベル　＝　安全が保障されている」と言っているかのように読めてしまいます。
しかも、Java に関しては現在完了ではなく過去時制に過ぎません。ですから、
「Javaを使い始めた頃には、そうするだけの理由がありました。しかし今ではシステムレベルプログラミングに、しかもJavaより安全が保障される言語で戻ってこられるのです。」
という感じです。I can は I could や I was able to ではないので……。

「panic!は私がRustにおけるエラーに対して不安を感じていなかったころから残っています。」
これは逆です。ひどいです。どうしてこうなった。
「不安を感じていたころの名残りです」なら分かります。
つまり、comfortable になりつつある進行形(途中)のころですから。
まだ「不安を払拭しきれなかったころの残滓」というわけですよね。

最後に
「Rustは無視できないエラーを発生させました。」
これを見て、もうこの翻訳モドキの続きを読む価値はないと思い、原文だけ読むことにしました。
なので、これ以降の内容に関するフィードバックはありません。

**Comment by tamo** [comment]
あ、訂正に私の名前は不要です。どうでもいいので早く直すか記事を取り下げるかすべきだと思います。

**Comment by mavcurry** [comment]
メールで頂きましたフィードバックの確認が遅れ、重ねてのお手数をおかけしてしまい申し訳ございません。
(同じくメールでいただきました「C90, C99, C11, C++98, C++11で異なる動作をするコード」のtypoについても確認・修正させていただきました)

頂きましたご指摘を確認し、サイト上へ反映させて頂きました。 
[http://postd.cc/a-year-of-rust-and-dns/](http://postd.cc/a-year-of-rust-and-dns/)

翻訳への的確なフィードバックをしていただき、大変感謝しております。
今後ともPOSTDをどうぞよろしくお願いいたします。
