### ISSUE TITLE
[翻訳フィードバック] どれだけ速く文字列からスペースを削除できるのか

### ISSUE THREAD

**Issue by kwatch** [postdcc/feedback#20]
翻訳で、わかりにくい or 日本語として不自然な箇所があったので、別の翻訳を提案します。

原文：
> It is going to be faster as long as most blocks of eight characters do not contain any white space. When this occurs, we are basically copying 64-bit words one after the other, along with a moderately expensive check that our superscalar processors can do quickly.

元訳：
> 8文字単位のブロックに空白がなければ、処理は速くなります。この時何が起きているかというと、基本的には64ビットのワードを1つ1つコピーしながら、スーパースカラな処理を高速でできる適度に高価なチェックを実行しています。

提案訳：
8文字ごとのブロックの大半が空白スペースを何も含まなければ、この方法はより高速です。この場合、ある程度動作コストがかかるチェックをスーパースカラプロセッサで高速に実行できるので、基本的には64ビット単位で次々とコピーするだけになります。

原文：
> This approach proposed by Robin Leffmann is very clever, and it is fast because it avoids penalties due to mispredicted branches.

元訳：
> 上記はRobin Leffmannによって提案された、分岐誤予測のペナルティを回避できるため、とても巧妙で速いアプローチです。

提案訳：
これはRobin Leffmannによって提案された、とても巧妙な方法です。分岐予測ミスによるペナルティを回避できるため、高速です。

**Comment by satomi-yako** [comment]
本記事に対するフィードバック、翻訳修正のご提案ありがとうございました。
参考にさせて頂き修正版を公開させて頂きましたので、ご報告させて頂きます。
今後とも、POSTDを何卒よろしくお願いいたします。
