### ISSUE TITLE
[翻訳フィードバック] Emacs、Guile、Emacs Lispの未来

### ISSUE THREAD

**Issue by iwaim** [postdcc/feedback#22]
* http://postd.cc/the-future-of-emacs-guile-and-emacs-lisp/

> GuileがSchemeや完全に無関係なオプションであるJava Scriptのような他の言語を同じようにサポートする限り

「Java Script」という表記がありますが、「JavaScript」が正しい表記ですし、原文もそのように記載されています。

名前の記載については、ただのtypoの指摘なので不要です。

**Comment by re-fort** [comment]
ご指摘ありがとうございます。
記述を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします。
