### ISSUE TITLE
[翻訳フィードバック] 信頼性の高いパスワードの生成 - #21

### ISSUE THREAD

**Issue by iwaim** [postdcc/feedback#24]
### 記事タイトル or URL

* http://postd.cc/passwords-entropy/

### フィードバック内容

#21 が再発しているようです。（といっても修正されたものは私は未確認）

名前は不要です。

**Comment by re-fort** [comment]
ご指摘ありがとうございます。
また、対応が遅れまして申しわけありません。
記述を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします。
