### ISSUE TITLE
[翻訳フィードバック] 信頼性の高いパスワードの生成 - Markdown syntax

### ISSUE THREAD

**Issue by iwaim** [postdcc/feedback#25]
### 記事タイトル or URL

* http://postd.cc/passwords-entropy/

### フィードバック内容

> UNIXの標準パスワードマネージャである[pass](https://www.passwordstore.org/)は、このタスクを有名な[pwgen](https://packages.debian.org/sid/pwgen)プログラムに委譲しています。

この部分のpassとpwgenですが、何らかの理由でMarkdownでのマークアップのまま表示されています。

なお、名前は不要です。

**Comment by re-fort** [comment]
ご指摘ありがとうございます。
また、対応が遅れまして申しわけありません。
記述を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします。
