### ISSUE TITLE
[翻訳フィードバック] 一から学ぶベジェ曲線

### ISSUE THREAD

**Issue by impepc** [postdcc/feedback#26]
### フィードバック内容
内容は面白いかと思いますが、できれば、元記事からアニメーションを持ってこれないでしょうか？

> このような独特な曲線も、3つの点だけで描くことができるとわかります！

と単なる図を見せられてもよくわかりません。

**Comment by re-fort** [comment]
ご指摘ありがとうございます。
元記事にならいSVGアニメーションを追加させていただきました！
今後ともPOSTDをよろしくお願いいたします。
