### ISSUE TITLE
[翻訳フィードバック] 私が書いた最速のハッシュテーブル - PART 1

### ISSUE THREAD

**Issue by rindoh** [postdcc/feedback#27]
### 記事タイトル or URL

私が書いた最速のハッシュテーブル - PART 1

### フィードバック内容

"更に、グラフの一番下に位置するテーブルのmax_load_factorは0.5％であり"

ここの"％"は不要ではないでしょうか。

**Comment by remore** [comment]
フィードバックありがとうございます。
おっしゃる通りtypoであり不要でしたので、%を削除いたしました。
今後ともPOSTDをよろしくお願いいたします。
