### ISSUE TITLE
[翻訳フィードバック] UIデザインにおけるボタン:スタイルの進化とベストプラクティス

### ISSUE THREAD

**Issue by yambe2002** [postdcc/feedback#28]
### 記事タイトル or URL
UIデザインにおけるボタン:スタイルの進化とベストプラクティス
http://postd.cc/buttons-in-ui-design-the-evolution-of-style-and-best-practices/

### フィードバック内容
最後の画像（Amazonの例）が元文と異なっています。

**Comment by re-fort** [comment]
ご指摘ありがとうございます。
画像リンクを修正させていただきました！
今後ともPOSTDをよろしくお願いいたします。
