### ISSUE TITLE
[翻訳フィードバック] #/usr/binとその同種の周辺を探る - under zsh

### ISSUE THREAD

**Issue by iwaim** [postdcc/feedback#29]
### 記事タイトル or URL
* http://postd.cc/adventures-in-usr-bin/

### フィードバック内容
《以下はzshの下をチェックする簡単な方法です。》ですが、「under zsh」はzshの下という意味ではなく、Zsh環境下という意味ですね。fcコマンドがBashやZshのビルドインコマンドだから、Zshを使っているということを明示しているのでしょう。（たとえばtcshだと実行できない）

最小限の修正の場合は『以下はzsh環境でチェックする簡単な方法です。』あたりでしょうか。

**Comment by mk2** [comment]
頂きましたご指摘を確認し、再度翻訳を検討し修正いたしました。
http://postd.cc/adventures-in-usr-bin/

翻訳への的確なフィードバックをしていただき、また別件のご指摘もいただき大変感謝しております。
今後ともPOSTDをどうぞよろしくお願いいたします。
