### ISSUE TITLE
[翻訳フィードバック] #/usr/binとその同種の周辺を探る - filter out commands only from today

### ISSUE THREAD

**Issue by iwaim** [postdcc/feedback#30]
### 記事タイトル or URL
* http://postd.cc/adventures-in-usr-bin/

### フィードバック内容
《fcを使いタイムスタンプを参照し、今日の分だけのコマンドを抽出しました。》の部分ですが、『fcを使いタイムスタンプを参照し、コマンドだけを抽出しました。』あたりが妥当な訳だと判断します。awkでコマンド部分**だけ**を抽出しているので。

実際には、タイムスタンプ出してても後の処理で何もしていないので、「タイムスタンプをみて、今日の分だけを抽出しよう」という当初の計画があったけど面倒になった（or コマンドが長すぎるわりには言いたいことに対して益しない）のでfcに「-146」とfcの出力数を決め打ちしたんじゃないでしょうか。
そういう意味では「from today」を訳出しないだけではなく、タイムスタンプ周りの話も取っ払う方が文章としては美しいかと。

**Comment by mk2** [comment]
頂きましたご指摘を確認し再度翻訳を検討しましたが、より原文に近い現在の訳が好ましいと判断させていただきます。
http://postd.cc/adventures-in-usr-bin/

※このissueは1週間後にcloseさせていただきます
