### ISSUE TITLE
[翻訳フィードバック] #/usr/binとその同種の周辺を探る - A simple clock

### ISSUE THREAD

**Issue by iwaim** [postdcc/feedback#31]
### 記事タイトル or URL
* http://postd.cc/adventures-in-usr-bin/#watch

### フィードバック内容
《シンプルなクロックは以下のようになります。》

間違ってはいませんが、現在日時を1秒毎に表示している例なのですから「シンプルな時計」でいいような。

**Comment by mk2** [comment]
頂きましたご指摘を確認し、再度翻訳を検討し修正いたしました。
http://postd.cc/adventures-in-usr-bin/

翻訳への的確なフィードバックをしていただき、また別件のご指摘もいただき大変感謝しております。
今後ともPOSTDをどうぞよろしくお願いいたします。
