### ISSUE TITLE
[翻訳フィードバック] #/usr/binとその同種の周辺を探る - peekfd

### ISSUE THREAD

**Issue by iwaim** [postdcc/feedback#32]
### 記事タイトル or URL
* http://postd.cc/adventures-in-usr-bin/#peekfd

### フィードバック内容
《保存時にvimの動作を監視します。》ですが、やっていることはvimプロセスの!/O監視です。I/O監視の結果を（例として）出力しているのですから、『保存時のvimの動作を監視します』ぐらいの意味ですね。

《いずれにせよ》の部分は、文脈を鑑みると原文自体がin any caseの用法を間違っているような気はします。

**Comment by mk2** [comment]
頂きましたご指摘を確認し再度翻訳を検討しましたが、修正をいれるほどの意味の乖離は存在せず現状の翻訳で問題ないと判断させていただきます。
http://postd.cc/adventures-in-usr-bin/

※このissueは1週間後にcloseさせていただきます
