### ISSUE TITLE
[翻訳フィードバック] 200行のコードへのブロックチェーンの実装

### ISSUE THREAD

**Issue by soyanakagawa** [postdcc/feedback#33]
### 記事タイトル or URL
http://postd.cc/a-blockchain-in-200-lines-of-code/
### フィードバック内容
記事下部で cURL と記載するはずの所がcRULになっています。

**Comment by re-fort** [comment]
ご指摘ありがとうございます。
また、対応が遅れまして申しわけありません。
記述を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします。
