### ISSUE TITLE
[翻訳フィードバック] 私はC言語を知らない

### ISSUE THREAD

**Issue by mohno** [postdcc/feedback#34]
### 記事タイトル or URL
http://postd.cc/i-do-not-know-c/
### フィードバック内容
5.について、C言語では大文字の「NULL」は null pointer をあらわすシンボルとして定義されており、文字の終わりを示す null character（'\0'）とは違うものです。原文は "null-terminated line" とありますが、wikipedia におけるヌル終端文字列　https://ja.wikipedia.org/wiki/%E3%83%8C%E3%83%AB%E7%B5%82%E7%AB%AF%E6%96%87%E5%AD%97%E5%88%97 のことですので、「ヌル(文字)で終わる行」などと訳せばよいでしょう。

**Comment by mk2** [comment]
頂きましたご指摘を確認し、再度翻訳を検討し修正いたしました。
http://postd.cc/i-do-not-know-c/

翻訳への的確なフィードバックをいただき大変感謝しております。
今後ともPOSTDをどうぞよろしくお願いいたします。
