### ISSUE TITLE
[翻訳フィードバック] Go言語のリアルタイムGC　理論と実践

### ISSUE THREAD

**Issue by yaneurao** [postdcc/feedback#35]
### 記事タイトル or URL

http://postd.cc/golangs-real-time-gc-in-theory-and-practice/

### フィードバック内容

> バージョンアップのたびにレイテンシが向上していることを知って

「レイテンシが向上している」という表現に、もやっとします。意味的には間違っていないのですが、「レイテンシが増えている」ようにも聞こえます。(「向上」の対義語が「低下」であるため、「レイテンシが低下する」の反対の意味ではないかと感じるのだと思います。)

ここは、「レイテンシが改善している」と訳すほうが良いと思います。

以下の記事も同様。
http://postd.cc/kernel-latency/

**Comment by re-fort** [comment]
ご指摘ありがとうございます。
記述を修正させていただきました！
今後ともPOSTDをよろしくお願いいたします。
