### ISSUE TITLE
[翻訳フィードバック] 大学院生のためのLLVM

### ISSUE THREAD

**Issue by musou1500** [postdcc/feedback#37]
### 記事タイトル or URL
http://postd.cc/llvm-for-grad-students/

### フィードバック内容
こちらの原文について，
> To stitch our new instruction into the code, we have to find all the places it’s used and swap in our new instruction as an argument. Recall that an Instruction is a Value: here, the multiply Instruction is used as an operand in another Instruction, meaning that the product will be fed in as an argument.

このように訳されていました．
> 新しい命令をコードに組み込むためには、命令が使われている場所を全て探し出し、新しい命令を引数として置き換えなくてはなりません。命令は値であることを思い出してください。複数の命令は、他の命令でオペランドとして使われているので、プロダクトは引数として送られることになります。

しかし，ここでの`the multiply Instruction`は，「複数の命令」ではなく「乗算命令」の意味ではないでしょうか．
また，`the product`についても，「積」という意味かと考えられますが，いかがでしょうか．

**Comment by mk2** [comment]
こちらご指摘の内容を反映させていただきました。

今後ともPOSTDをよろしくお願いいたします。ありがとうございました。
