### ISSUE TITLE
[翻訳フィードバック] MXNet API入門 パート1

### ISSUE THREAD

**Issue by kitsuyui** [postdcc/feedback#38]
### 記事タイトル or URL

[MXNet API入門 パート1](http://postd.cc/an-introduction-to-the-mxnet-api-part-1/)

### フィードバック内容

> このため、MXNetのWebサイトで提供されているDocker画像をそれぞれ、CPU環境およびGPU環境に使うよう強く忠告します

「Docker画像」ではなく「Dockerイメージ」がふさわしいとおもいます。

**Comment by mk2** [comment]
こちらいただいたフィードバックを反映させていただきました。ありがとうございます。

今後ともPOSTDをよろしくお願いいたします。
