### ISSUE TITLE
[翻訳フィードバック] Git Undo エイリアスを定義する

### ISSUE THREAD

**Issue by clicktx** [postdcc/feedback#39]
### 記事タイトル or URL

[Git Undo エイリアスを定義する | インフラ・ミドルウェア | POSTD](http://postd.cc/git-undo/)

### フィードバック内容

> refloをgit resetコマンドと合わせて使う場合の構文は、以下のようになります。
> `git reset –hand master@{1}`

コマンドにtypoがあるようです。

正しくは `git reset --hard master@{1}` でしょうか？

**Comment by mk2** [comment]
フィードバックありがとうございます。こちらご指摘の通りtypoでしたので、修正いたしました。

今後ともPOSTDをよろしくお願いいたします。ありがとうございました。
