### ISSUE TITLE
[翻訳フィードバック] バージョンの充足可能性問題 (Section「代替案？」)

### ISSUE THREAD

**Issue by koba-e964** [postdcc/feedback#4]
URL: https://research.swtch.com/version-sat
Section「代替案？」において、「この問題を解決できるツールをビルドすべきではありませんし」は、「この問題を解決できるツールをビルドすべきではないかもしれませんし」であるべきです。
名前の掲載はどちらでも構いません。

**Comment by mk2** [comment]
頂きましたご指摘を確認し、再度翻訳を検討し修正いたしました。
http://postd.cc/version-sat/

翻訳への的確なフィードバックをしていただき、大変感謝しております。
今後ともPOSTDをどうぞよろしくお願いいたします。
