### ISSUE TITLE
[翻訳フィードバック] Webサイト開発にCSS in JavaScriptを使うのはやめよう

### ISSUE THREAD

**Issue by terrierscript** [postdcc/feedback#40]
### 記事タイトル or URL
Webサイト開発にCSS in JavaScriptを使うのはやめよう
http://postd.cc/stop-using-css-in-javascript-for-web-development-fa/

### フィードバック内容

> 神話9：応答型コンポーネントを開発できる

という訳についてですが、原文を見ると
`Myth 9: It allows developing responsive components`
とあります。

これであれば「`神話9：レスポンシブなコンポーネントを開発できる`」とする方が一般的で伝わりやすい表現かと思われます。

**Comment by satomi-yako** [comment]
本記事に対するフィードバックありがとうございました。
修正版を公開させて頂きましたので、ご報告させて頂きます。
（#41 も修正させて頂きました）
今後とも、POSTDを何卒よろしくお願いいたします。
