### ISSUE TITLE
[翻訳フィードバック] Webサイト開発にCSS in JavaScriptを使うのはやめよう

### ISSUE THREAD

**Issue by sghkk** [postdcc/feedback#41]
### 記事タイトル or URL
[Webサイト開発にCSS in JavaScriptを使うのはやめよう](http://postd.cc/stop-using-css-in-javascript-for-web-development-fa/)
### フィードバック内容
> 数え切れないほど多くの命名規則（例：BEMによって

括弧が閉じられてないようです。「（例：BEM）」が適切だと思います。

**Comment by satomi-yako** [comment]
本記事に対するフィードバックありがとうございました。
修正版を公開させて頂きましたので、ご報告させて頂きます。
（#40 も修正させて頂きました）
今後とも、POSTDを何卒よろしくお願いいたします。
