### ISSUE TITLE
[翻訳フィードバック] JavaScript モジュールの現状

### ISSUE THREAD

**Issue by uasi** [postdcc/feedback#42]
### 記事タイトル or URL
[JavaScript モジュールの現状 | プロダクト・サービス | POSTD](http://postd.cc/the-state-of-javascript-modules/)

### フィードバック内容
> ここでも構文は似ていますが、CJSによってエクスポートが名付けられていないことは無視します。

> Again, the syntax looks pretty similar, but it ignores the fact that there are no named exports in CJS.

「ここでも構文は似ていますが、実際は CJS には名前付きエクスポートがありません」

---

> 1\. CJSの厳しい後方互換性

> 1\. Strict backwards compatibility with CJS

「CJS との厳密な後方互換性」

---

> CJSの `await.import()` と比較してください。

`await import()`

---

> 上述した利点やtree shaking、独創的なブラウザ互換性のような利点がESMにはある

> such as tree shaking and browser compatibility out of the box

ここの out of the box は設定や変更が不要でそのまま使えることを表します。「変更不要でブラウザと互換性があるなどの利点が〜」でいいと思います。

---

> Node.jsのようなパスルックアップを行うことができなくなります。

> They _[browsers]_ will not be able to perform a path lookup like Node.js does.

「ブラウザはNode.jsが行うようなパスのルックアップを行うことができません」

**Comment by mk2** [comment]
こちら頂いたフィードバックをもとに翻訳を修正しました。

> 「ここでも構文は似ていますが、実際は CJS には名前付きエクスポートがありません」

ここについては、「無視」を消してしまうと原文から離れてしまうと判断したため、少し変えてあります。

丁寧なご指摘大変助かりました。ありがとうございます。

今後ともPOSTDをよろしくお願いいたします。
