### ISSUE TITLE
[翻訳フィードバック] Railsの基本理念 : Railsの生みの親が掲げる8つの原則

### ISSUE THREAD

**Issue by koic** [postdcc/feedback#43]
### 記事タイトル or URL

http://postd.cc/rails-doctrine

### フィードバック内容

良記事の翻訳ありがとうございます。
本記事について [rubyonrails.org](http://rubyonrails.org/doctrine) 本家への翻訳 Pull Request も受け付けているようですので、本家掲載でも読めるようになるとより記事が広まる契機になって良いかなと思いました。

参考 rails/homepage#91

**Comment by mk2** [comment]
貴重なご意見をありがとうございます。

本家にPRを出したい気持ちはあるのですが、PRを出すにあたって体裁を整えたHTMLへの変換をしないといけないので、今現在でのPOSTD運営チームではその対応時間を捻出できないという結論に至りました。

今後別の方法、またはPOSTD運営チームで対応するための十分な時間が捻出できた場合は再度検討させていただければと思っております。

今後ともPOSTDをよろしくお願いします。

**Comment by koic** [comment]
承知しました。ご回答ありがとうございました。いつもありがとうございます。
