### ISSUE TITLE
[翻訳フィードバック] Angular 2/4が狭量で遅すぎる理由

### ISSUE THREAD

**Issue by taxpon** [postdcc/feedback#44]
### 記事タイトル or URL
http://postd.cc/why-angular-2-4-is-too-little-too-late/

#### Typo:
- ✕
    - Reactのダウンロース数が3倍以上で、
- ◯
    - Reactのダウンロード数が3倍以上で、

**Comment by mk2** [comment]
こちらいただいたフィードバックを反映させていただきました。ありがとうございます。

今後ともPOSTDをよろしくお願いいたします。
