### ISSUE TITLE
[翻訳フィードバック] SQLトランザクション分離 実践ガイド

### ISSUE THREAD

**Issue by jpwgad** [postdcc/feedback#45]
### 記事タイトル or URL
http://postd.cc/practical-guide-sql-isolation/

### フィードバック内容
誤：行 y を搔き込む
正：行 y を書き込む

**Comment by mk2** [comment]
こちらフィードバックを反映させていただきました。ありがとうございました。

今後ともPOSTDをよろしくお願いいたします。
