### ISSUE TITLE
[翻訳フィードバック] SQLトランザクション分離 実践ガイド

### ISSUE THREAD

**Issue by zyake** [postdcc/feedback#46]
### 記事タイトル or URL
http://postd.cc/practical-guide-sql-isolation/

### フィードバック内容
「トランザクション現象」という訳では意図が伝わりにくいので、英文そのままにするか、次のMSのドキュメントのように「副作用」と言い換えてしまったほうが伝わると思います。
https://msdn.microsoft.com/ja-jp/library/jj856598(v=sql.120).aspx

本文中の以下の箇所は「同時」ではなく「並列に実行すると」といった形で訳さないと誤解を招いてしまいます。
(concurrentやsimultaneouslとat the same timeではニュアンスが全く異なります)
「しかし、トランザクションを同時に実行すると」
「例えば、2人の人が1枚だけ残っているイベントチケットを同時に買おうとするとしましょう。」
「2人のユーザが同時に全ての行に一致する色の値を持たせようとしますが、」

**Comment by mk2** [comment]
ご指摘ありがとうございます。

「トランザクション現象」については、「トランザクション副作用」のほうが確かにわかりやすいと判断し、文言を入れ替えました。

また、「並列」を「同時」といっている部分については、

- 「しかし、トランザクションを同時に実行すると」
  - → 並列へ変更
- 「例えば、2人の人が1枚だけ残っているイベントチケットを同時に買おうとするとしましょう。」
  - →「同時に(並列に)」の形である程度文としての意味が通るような変更
- 「2人のユーザが同時に全ての行に一致する色の値を持たせようとしますが、」
  - →「同時に(並列に)」の形である程度文としての意味が通るような変更

という形でご指摘内容を反映させていただきました。また何かありましたらご指摘いただけると助かります。

今後ともPOSTDをよろしくお願いいたします。
