### ISSUE TITLE
[翻訳フィードバック] C++11スマートポインタで避けるべき過ち Top10

### ISSUE THREAD

**Issue by cbh34680** [postdcc/feedback#47]
### 記事タイトル or URL
http://postd.cc/top-10-dumb-mistakes-avoid-c-11-smart-pointers/  

### フィードバック内容
[過ちその4： shared_ptrの初期化にmake_sharedを使わない]  

×: 一方、shared_ptrでは、C++コンパイラは...
〇: 一方、make_sharedでは、C++コンパイラは...

ではないかと思いますが、いかがですか ?

**Comment by mk2** [comment]
フィードバックありがとうございます。

原文を確認したところ、ご指摘の通りの訳が適切だと判断しましたので、修正させていただきました。

とても助かりました。今後ともPOSTDをよろしくお願いいたします。
