### ISSUE TITLE
[翻訳フィードバック] #Anthony Calandra / モダンC++の機能

### ISSUE THREAD

**Issue by cbh34680** [postdcc/feedback#48]
### 記事タイトル or URL
http://postd.cc/modern-cpp-features/#move-semantics  

### フィードバック内容
[移動セマンティクス]  

×: 例えば、std::unique_ptrsといった、一意のオブジェクト...  
〇: 例えば、std::unique_ptrといった、一意のオブジェクト...  

ではないかと思いますが、いかがですか ?

**Comment by mk2** [comment]
フィードバックありがとうございます。

こちら原文を確認し、末尾のsは日本語に訳す際不要なものであると判断できたので、いただいたフィードバックを反映させていただきました。

今後ともPOSTDをよろしくお願いいたします。
