### ISSUE TITLE
[翻訳フィードバック] gh-ost：GitHubのMySQL向けオンライン・スキーマ・マイグレーションツール

### ISSUE THREAD

**Issue by asayamakk** [postdcc/feedback#49]
### 記事タイトル or URL
http://postd.cc/gh-ost-github-s-online-migration-tool-for-mysql/
### フィードバック内容

原文
> At GitHub we use the common master-replicas architecture and utilize the reliable InnoDB engine.

記事
> GitHubでは、共通マスター&レプリカ・アーキテクチャを使って、信頼性の高いInnoDBエンジンを利用します。

提案

GitHubでは、一般的なマスター&レプリカ構成で、信頼性の高いInnnoDBを利用しています。

**Comment by re-fort** [comment]
修正提案ありがとうございます！
確認が遅くなってしまいましたが、記述を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします！
