### ISSUE TITLE
[翻訳フィードバック] 部分文字列とRegExpの領域の冒険 (Section「パート2：less_dartの登場」)

### ISSUE THREAD

**Issue by koba-e964** [postdcc/feedback#5]
URL: http://postd.cc/making-less-dart-faster/
Section「パート2：less_dartの登場」
「Dart VMはこれを実装していません」は「Dart VMはこれを**O(1)の演算としては**実装していません」であるべきです。
また、「Dart VMが実装しているのは、RegExp.matchAsPrefixの方法です」は「Dart VMが実装しているのは、RegExp.matchAsPrefixの**メソッド**です」であるべきです。(いずれも太字は差分を表しています)

名前の掲載はどちらでも構いません。

**Comment by satomi-yako** [comment]
本記事に対するフィードバックありがとうございました。
また、確認や対応などが遅れてしまいまして申し訳ございませんでした。 

>「Dart VMはこれを実装していません」は「Dart VMはこれをO(1)の演算としては実装していません」であるべきです。
V8ランタイムでは実装しており、Dart VMではしていないという意味合いでしたため、後者には「O(1)の演算として」という言葉を外して記載しておりました。しかし、ご指摘頂いたということは、わかりづらい表現だったのだと思います。ご不便をおかけして申し訳御座いません。

>また、「Dart VMが実装しているのは、RegExp.matchAsPrefixの方法です」は「Dart VMが実装しているのは、RegExp.matchAsPrefixのメソッドです」であるべきです。
確認しましたところ、たしかに誤った表現でした。

こちら、双方ともに修正版を公開させて頂きましたので、ご報告させて頂きます。
今後とも、POSTDを何卒よろしくお願いいたします。
