### ISSUE TITLE
[翻訳フィードバック] Unixコマンド"yes"についてのちょっとした話

### ISSUE THREAD

**Issue by bellbind** [postdcc/feedback#50]
### 記事タイトル or URL

- http://postd.cc/a-little-story-about-the-yes-unix-command/

### フィードバック内容

> 重要なのは、メモリの配列を確実にするために、バッファサイズが4の倍数であることです。

> The important part is, that the buffer size is a multiple of four, to ensure memory alignment.

「メモリアラインメント」は、少なくとも配列のことではありません。たとえば4バイトのメモリを読み書きするときのアドレス値を、後ろ2ビットが0のアドレス(=4の倍数)に"整える"、という話です。ただ、バッファサイズを倍数にするのは、バッファの末尾で(遅くなる)余り処理を入れないためですが。

CPUアーキテクチャ依存の話ですが、そうしてあれば高速に複数バイトの読み書きができたり、そもそも非アラインメントなアドレスでの読み書きが不可能なCPUもあります(そういう場合は、複数回メモリアクセスしてビット演算で構成する)。ユーザーコードでもmemsetとかでは、アラインメントされたアドレスの場合、4バイトや8バイト単位でコピーします。

- https://github.com/lattera/glibc/blob/master/string/memset.c

あと元記事の説明とは違い、今メジャーな64ビット環境なら8の倍数(下3ビットが0)で揃えると思います。1024も8192も8の倍数だけど。

- 参考: http://e-words.jp/w/%E3%82%A2%E3%83%A9%E3%82%A4%E3%83%A1%E3%83%B3%E3%83%88.html

**Comment by remore** [comment]
頂きましたご指摘を確認し、再度翻訳を検討し修正いたしました。(s/メモリの配列/メモリのアラインメント/)
http://postd.cc/a-little-story-about-the-yes-unix-command/

翻訳への的確なフィードバックをいただき大変感謝しております。
今後ともPOSTDをどうぞよろしくお願いいたします。
