### ISSUE TITLE
[翻訳フィードバック] Haskellと共に4年間を歩んだ起業家の視点

### ISSUE THREAD

**Issue by masmatsum** [postdcc/feedback#51]
### 記事タイトル or URL
[Haskellと共に4年間を歩んだ起業家の視点 | プログラミング | POSTD]
http://postd.cc/haskell-in-a-startup/

### フィードバック内容

修正したほうが良さそうと思った点がいくつかあります。
なお私は
・関数型言語については勉強中で、 Haskell のライブラリについての知識はあまりありません
・英語は好きですが、留学経験等はありません
という感じですが、気づいたことについて書きました。

日本語文を読んで違和感を持ったところを中心に原文を見ていったので、全部を読んだわけではありません。

1.
(原文: Purity lets you reason more easily about your program.)
純粋性のため、プログラムの論理づけが容易です。
→純粋性のため、プログラムの推論が容易です。

動詞としての reason は「推論する」という意味です。

参考：
https://ejje.weblio.jp/content/reason
https://ejje.weblio.jp/content/reasoning

「論理づけ」という言い方は普通しないと思います。
なお、試しに「論理づけ」でググったら、全然関係なさそうな特許関連のことが出てきました（しかも件数が少ない）。なのでやはり「推論」が良いと思います。

2.
(原文: purity gives you much more confidence when reasoning about code.)
言語が純粋なので、自信を持ってコードに理論づけできます。
→言語が純粋なので、自信を持ってコードについて推論できます。

上記と同様です。

3.
(原文: In more practical terms, one of our biggest complaints with Haskell was basic tool support.)
より実用的な点では、Haskellで私が最も不満なのは、基本的なツールのサポートです。
→より実用的な点では、Haskellで私が最も不満なのは、基本的なツールのサポートでした。

was なので「でした」ですね。
それに、この文章のあとに 「Stack によって良くなった」のような内容が書かれていることからも、「でした」のほうが適切だと思います。

4.
(原文: strict languages)
厳格な言語
→正格な言語
（または、「正格評価の言語」など？）

遅延評価とかそういう文脈では、 strict は「厳格」ではなく「正格」と訳します。
（"strict evaluation"＝「正格評価」、 "non-strict evaluation"＝「非正格評価」など）

参考：
https://ja.wikipedia.org/wiki/%E8%A9%95%E4%BE%A1%E6%88%A6%E7%95%A5#.E6.AD.A3.E6.A0.BC.E3.81.AA.E8.A9.95.E4.BE.A1
https://en.wikipedia.org/wiki/Strict_programming_language

5.
(原文: Haskell’s type system removes the need for a large class of tests required in weaker languages to catch inconsistencies.)
Haskellの型システムは、不一致を見つけるために、弱い型付けの言語で必要とされる大きなクラスのテストの必要性を取り除きます。
→
・Haskellの型システムは、不一致を見つけるために弱い型付けの言語で必要とされる、大きなクラスのテストの必要性を取り除きます。
・Haskellの型システムは、弱い型付けの言語で不一致を見つけるために必要な、大きなクラスのテストの必要性を取り除きます。

"to catch inconsistencies" は "removes" ではなく "a large class of tests" にかかっていると思います。
※「不一致を見つける」ってなんか変ですね・・・。「不一致」は「矛盾」とかのほうがいいかもしれません。

6.
(原文: The type system can ensure certain kinds of consistency, ...)
ただ、型システムはある種の整合性を保証してくれますが、整合性のとれたプログラムも誤った動きをすることがあるのです。
→型システムはある種の整合性を保証してくれますが、整合性のとれたプログラムも誤った動きをすることがあるのです。

「ただ」は不要です。
「ただ」があることによって、前の文「私は、テストは重要だと考えています。」からの意味のつながりが変になっています。

7.
イテレーション速度が早く
→イテレーション速度が速く

8.
複雑性を対処したり
→複雑性に対処したり

9.
(原文: You will worry less about the server crashing when you go to sleep.)
就寝する際に、サーバがクラッシュしてしまう心配もわずかで済みますし
→
・就寝時に、サーバがクラッシュしないかと心配することもわずかで済みますし
・就寝時に、サーバのクラッシュを心配することも少なくなりますし
など。
この文章で「就寝時に」が修飾するのは「サーバがクラッシュする」ではなく「心配する」ですよね。
サーバーがクラッシュし得るのは、就寝時（ベッドに入るとき）というよりは、寝ている間でしょう。

以上です。

**Comment by mo-ry** [comment]
修正提案ありがとうございます！
頂きました指摘をもとに、翻訳を検討し修正いたしました。
今後ともPOSTDをよろしくお願いいたします。
