### ISSUE TITLE
[翻訳フィードバック] 私のURLはあなたのURLとは違う : curl作者の語る、URLの仕様にまつわる苦言

### ISSUE THREAD

**Issue by critical-bug** [postdcc/feedback#52]
### 記事タイトル or URL
私のURLはあなたのURLとは違う : curl作者の語る、URLの仕様にまつわる苦言
http://postd.cc/my-url-isnt-your-url/

### フィードバック内容
|原文|現状|修正案|理由,補足|
|----|----|----|----|
|It means it’ll handle too many slashes, embedded white space as well as non-ASCII characters.|つまり、スラッシュ、埋め込まれた空白、それに非ASCII文字を、あまりにも多く処理しなければならないのです。|つまり、多すぎるスラッシュ、埋め込まれた空白、それに非ASCII文字を処理しなければならないのです。|記事読めば分かるけど、URLにはもともとスラッシュ入ってて、しかし人間がその数を増減させがちなのが問題|
|I’m mentioning this since people will often think of what you can enter there as a “URL”.|私がこの点についてふれた理由は、人は普通、入力が可能なら、それを”URL”と考えがちだからです。|私がこの点についてふれた理由は、人はそこに入力が可能なものを”URL”と考えがちだからです。|there は address bar|
|While it was probably more notable years ago when the browsers displayed it more prominently, the :// (colon-slash-slash) sequence will be high on the list.|何年も前、ブラウザにURLがはっきりと表示されていた頃には、リストで://（コロン-スラッシュ-スラッシュ）を目にすることが多かったと思われます。|ブラウザがURLをよりはっきりと表示したのはおそらく何年も前ですが、://（コロン-スラッシュ-スラッシュ）はリストの上位に来るでしょう。|「何と答えるでしょうか？」の答え。notable 分からなかった。more 〜 more つながっているのかは分からなかった。|

**Comment by re-fort** [comment]
ご指摘ありがとうございます！
いただいた修正案をもとに修正させていただきました。

最後のものだけ、意訳して、
`ブラウザがURLをよりはっきりと表示したのはおそらく何年も前ですが、://（コロン-スラッシュ-スラッシュ）は回答リストの上位になるでしょう。`
とさせていただきました。

今後ともPOSTDをよろしくお願いいたします。
