### ISSUE TITLE
[翻訳フィードバック] Haskellで生産性を高める-Pythonからの移行

### ISSUE THREAD

**Issue by masmatsum** [postdcc/feedback#54]
### 記事タイトル or URL

[Haskellで生産性を高める-Pythonからの移行 | プログラミング | POSTD]
http://postd.cc/becoming-productive-in-haskell/

### フィードバック内容

日本語文を読んで違和感を持ったところを中心に原文を見ていったので、原文全てを読んだわけではありません。

1.
(原文: This is more of a thought on moving from a dynamic language to a static language, )
動的言語から静的言語への移行において、これは考えというわけではありませんが、
→これはどちらかというと動的言語から静的言語への移行に関しての考えなのですが、

"be more of" は「どちらかと言えば～である」「むしろ～である」という意味らしいです。
参考：
http://blog012.ooenoohji.com/entry/be-more-of

2.
(原文: If they’re named well, this allows you to write functions that are easy to read.)
また、きちんと名前が付けられている場合は、読みやすい関数を書くことも可能です。
→きちんと名前が付けられていれば、読みやすい関数を書くことができます。

「また、」および「書くことも可能」の「も」が引っかかります。何かとの同列ではないと思うからです。
（おそらく、 they は smaller functions を、 this は1つ前の文全体を、それぞれ指していると思います。
つまり、「関数を、小さい関数で構成する」 ことによって、（関数名が変でなければ）関数を読みやすくできる、という話だと思います。）

3.
(原文: Keep it simple, a URL that shows a sudoku puzzle. Then, a URL that produces JSON of a sudoku puzzle.)
Webサイトはあくまでシンプルに、URLは数独を示すものにしましょう。このURLから、数独のJSONが生成されます。
→Webサイトはあくまでシンプルに、URLは数独を表示するものにしましょう。その後は、数独のJSONを生成するURLにしてみましょう。

私もあまり自信がないですが、少なくとも 
- URL の後の that は関係代名詞である
- 以下の2つが同列の関係になっている
  - a URL that shows a sudoku puzzle
  - a URL that produces JSON of a sudoku puzzle

のは確かです。
なので、「このURLから、数独のJSONが生成されます。」はおかしいと思います。
また、上のような同列関係があるなら、 show は「（Webページとして）表示する」という意味になる気がします。

**Comment by mo-ry** [comment]
フィードバックありがとうございます！
こちらを基に記事を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします！
