### ISSUE TITLE
[翻訳フィードバック] Python 3を使うべきでない場合（なんてない）

### ISSUE THREAD

**Issue by masmatsum** [postdcc/feedback#55]
### 記事タイトル or URL

[Python 3を使うべきでない場合（なんてない） | プログラミング | POSTD]
http://postd.cc/case-python-3/

### フィードバック内容

(原文: Maybe the designers got some things wrong, but on the whole, )
しかし設計者が何かを間違ったのか、総合的には、
→設計者が何かを間違ったのかもしれませんが、総合的には、

**Comment by mo-ry** [comment]
フィードバックありがとうございます！
こちらを基に記事を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします！
