### ISSUE TITLE
[翻訳フィードバック] Rubyにはウンザリ！動的型付け、副作用、およびオブジェクト指向プログラミング全般からの考察

### ISSUE THREAD

**Issue by masmatsum** [postdcc/feedback#56]
### 記事タイトル or URL

[Rubyにはウンザリ！動的型付け、副作用、およびオブジェクト指向プログラミング全般からの考察 | プログラミング | POSTD]
http://postd.cc/sick-of-ruby-dynamic-typing-side-effects-object-oriented-programming/

### フィードバック内容

1.
(原文: requiring a module that ships with the stdlib )
stdlibが搭載されているモジュールをrequireすると、
→stdlibに搭載されているモジュールをrequireすると、

2.
(原文: and code that simply doesn’t compile when not structured correctly.)
そして正しくなければ使えないというだけのシンプルなコードが
→そして、正しく組み合わせなければコンパイルが通らないコードが

simply は副詞であり、「シンプルな」ではありません。訳すとしたら「単に」と訳すのでしょうが、 simply は強調の意味などにも使われるようなので、訳出はしませんでした。

なお、自動詞としての compile は「コンパイルされる」または「コンパイルが通る」の意味です。

3.
(原文: minimize mutation and side effects to as few places as possible)
→突然変異や副次的動作を可能なかぎり最小化している
状態変化や副作用を可能なかぎり最小化している

mutation は、プログラミングの文脈では「状態を変えること」を指します（オブジェクトのフィールド変数の値を変えたり、グローバル変数の値を変えるなど）。
参考： [イミュータブル - Wikipedia]
https://ja.wikipedia.org/wiki/%E3%82%A4%E3%83%9F%E3%83%A5%E3%83%BC%E3%82%BF%E3%83%96%E3%83%AB
mutation に定訳があるのかどうか知りませんが、上の参考ページには「状態が変化する」「状態が変更される」というフレーズがあるので、上記の訳でどうでしょう。

side-effect はふつう「副作用」といいます。
参考： [副作用 (プログラム) - Wikipedia]
https://ja.wikipedia.org/wiki/%E5%89%AF%E4%BD%9C%E7%94%A8_(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0)

4.
(原文: and can infer types - no Java verbosity required.)
型を推測することができます – Javaの冗長性は不要。
→型推論があります – Javaの冗長性は不要です。

type inference は「型推論」です。
参考： [型推論 - Wikipedia]
https://ja.wikipedia.org/wiki/%E5%9E%8B%E6%8E%A8%E8%AB%96

なので、推測よりは推論と訳したほうがいいかと思います。

5.
(原文: If it compiles, it oftentimes just works)
コンパイルするだけで実行できる。
→コンパイルが通れば、多くの場合は動く。

リンク先の "Why Haskell just works" のページの冒頭に

>A lot of people experience a curious phenomenon when they start using Haskell: Once your code compiles it usually works. 

とあるとおりです。
「コンパイルするだけで実行できる。」だと、「他の言語ではコンパイルの他に（何かの）プロセスが必要だが、 Haskell ではそうではない」のように読めてしまうので良くないと思います。

**Comment by mo-ry** [comment]
フィードバックありがとうございます！
頂いた指摘をもとに記事を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします！
