### ISSUE TITLE
[翻訳フィードバック] 100万回のWebSocket接続とGo

### ISSUE THREAD

**Issue by yoshi44ever** [postdcc/feedback#57]
### 記事タイトル or URL
http://postd.cc/100万回のwebsocket接続とgo/

### フィードバック内容
.mdのマークアップが崩れているようです。  
preとかpが入り乱れています。

**Comment by re-fort** [comment]
フィードバックありがとうございます！
修正させていただきました！
今後ともPOSTDをよろしくお願いいたします！
