### ISSUE TITLE
[翻訳フィードバック] IPFS入門 : 新たなP2Pハイパーメディア分散プロトコル

### ISSUE THREAD

**Issue by june29** [postdcc/feedback#58]
### 記事タイトル or URL

IPFS入門 : 新たなP2Pハイパーメディア分散プロトコル
http://postd.cc/an-introduction-to-ipfs/

### フィードバック内容

翻訳文中にある

> 小さなファイル（256kB以下）

は、原文には

> A small file (< 256 kB)

とあるので「256kB未満」なのではないか？と思いました。というのも、

> 大きなファイル（256kB以上）は、256kB以下のファイルの塊に対するリンクのリストと

を読むと「じゃあ、ちょうど 256kB のときはどうなるのだ？」という疑問が生じました。

**Comment by remore** [comment]
フィードバックありがとうございます。(Hi from POSTD team ;))

ご指摘の箇所ですが私も読んでいて疑問に思いました。その上で原文を読んでいると、文章表現の中に`< 256 kB`と`> 256 kB`の2種類が出てくるのですが、ちょうど256kbのとき（`= 256kb`）については原文でも文章表現上は記述されていないようでした。

これを踏まえて文章の意図をもう１度考えてみると、チャンクを256kb単位で切っていくという意味だと思われますので、修正方針としては`< 256 kB`を256kb以下としている部分は是とし、`> 256 kB`が256kb以上となっている部分を修正する案を考えました。

この方針に基き、下記文章を

> 大きなファイル（256kB以上）は、256kB以下のファイルの塊に対するリンクのリストと

以下のように原文そのままの表記に修正しました。

> 大きなファイル（> 256kB）は、256kB以下のファイルの塊に対するリンクのリストと

いったん上記内容でクローズしますが、不明な点があればまたご連絡頂けると嬉しいです。
今後ともPOSTDをどうぞよろしくお願いいたします。

**Comment by remore** [comment]
その後再度読み直しましたが、原文に忠実であろうとするならば、256kb以下としてある部分も、256kbより小さい あるいは < 256kb の表現に戻すなどした方が良いかもしれません。

別の予定に取り掛かっており修正後ほどになりますが、こちらも追って修正するようにします。

**Comment by june29** [comment]
さわださん、反応ありがとうございます :relaxed:

コメントを受けて、ぼくも「実装はどうなっているんだ…？」とさらなる興味を持ちましたので、なにかわかり次第ここで共有したいと思います。

IPFS はおもしろい仕組みですね。素敵な翻訳のおかげで母国語で情報を得ることができて助かりました。ありがとうございます :v:

**Comment by remore** [comment]
すごく雰囲気でしか読めてないのですが、[この辺のやり取り](https://github.com/ipfs/go-ipfs/issues/2122)など見てもやはり256KiB以下という意味合いで本文を読むのがどうも正しそうです。

しかしながら確実に裏が取れているわけでもないので、まずは原文に忠実に、`256kB以下`としてある部分も`256kBより小さい`にするかまたは`< 256kB`という表現に戻すかのどちらかの修正を加えておきました。

管理の都合上ひとまずチケットクローズはしますが、追加の共有や新規チケットもいつでも歓迎です🎅 IPFS面白いですね。僕もこれをきっかけにIPFSを知って興味が持てたので、ちょっと今後気にしてみてみようと思います😃 フィードバックありがとうございました！
