### ISSUE TITLE
[翻訳フィードバック] Goでクリーンアーキテクチャを試す

### ISSUE THREAD

**Issue by ReSTARTR** [postdcc/feedback#59]
### 記事タイトル or URL

Goでクリーンアーキテクチャを試す
http://postd.cc/golang-clean-archithecture/

### フィードバック内容

- ドメイン
- レイヤ
- ドメインレイヤ

という用語が混在しているように見受けられます。
原文においては一貫して`layer`という表現が用いられていますし、単純に「レイヤ」と訳してはいかがでしょうか。

たとえば

> 私のプロジェクトでも4つのドメインを使うことにしました

は、

> 私のプロジェクトでも同様に4つのレイヤに分割しました

くらいの表現になるかなと。

もともとのクリーンアーキテクチャーの説明でも「ドメイン」という表現は使われていませんし、「ドメイン」という表現に置き換えることもできないと思います。

https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html

**Comment by remore** [comment]
フィードバックありがとうございます。確認したところ、仰る通りUncle BobのClean Architectureに関する記事原文には `domain` という文字が登場しないため、不用意に `ドメイン` という言葉を用いるのは混乱を招く恐れがあるように思われました。

当初翻訳者の意図としては、恐らくですが今回のサンプルコードとされているGitHubプロジェクトの[READMEの記述](https://github.com/bxcodec/go-clean-arch/blame/df1e86e84064a753dae82c025116257fbc7cc4dc/README.md#L14)や、[元記事のコメント](https://medium.com/@imantumorang/hi-gustavo-diaz-thanks-for-your-response-3916e5146506)等も参考にしながら訳されたものと思われますが、中途半端な引用により元記事の意図が不正確になってしまっている状態ですので、ご提案頂いた通り全て `レイヤ` という言葉に統一されるように訳文を修正しました。

今後ともPOSTDをよろしくお願いいたします。
