### ISSUE TITLE
[翻訳フィードバック] Webフレームワークとは何か

### ISSUE THREAD

**Issue by smori1983** [postdcc/feedback#60]
### 記事タイトル or URL

http://postd.cc/what-is-a-web-framework/

### フィードバック内容

**Djangoでのルーティング** の文章の翻訳修正です。

#### 原文

> These regular expressions can be arbitrarily complex and include both keyword and positional parameters.

#### 日本語訳

> これらの正規表現は任意の複素数を扱うことができ、キーワードと位置パラメータの両方を持つことができます。

は下記のような日本語が適していると思います。

> これらの正規表現は任意の複雑さのものを扱うことができ、キーワードと位置パラメータの両方を持つことができます。

**Comment by siminzhuo** [comment]
本記事に対するフィードバック、翻訳修正のご提案ありがとうございました。
参考にさせて頂き修正版を公開させて頂きましたので、ご報告させて頂きます。
今後とも、POSTDを何卒よろしくお願いいたします。
