### ISSUE TITLE
[翻訳フィードバック] 優秀な面接者に共通するものとは？　数千の実例を調べてみました。- 後編

### ISSUE THREAD

**Issue by owl-bo** [postdcc/feedback#61]
### 記事タイトル or URL
優秀な面接者に共通するものとは？　数千の実例を調べてみました。- 後編
http://postd.cc/what-do-the-best-interviewers-have-in-common-we-looked-at-thousands-of-real-interviews-to-find-out/

### フィードバック内容

『###高評価 >冒頭で面』
この部分はマークダウンのミスでは？

**Comment by siminzhuo** [comment]
フィードバックありがとうございます。
記事を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします!
