### ISSUE TITLE
[翻訳フィードバック] 紙と鉛筆でビットコインをマイニング：1日に0.67ハッシュ

### ISSUE THREAD

**Issue by yaneurao** [postdcc/feedback#62]
### 記事タイトル or URL
https://postd.cc/mining-bitcoin-with-pencil-and-paper/

### フィードバック内容

> 手作業によるハッシングの1018倍の速さです。

人間の計算能力がいまどきのPCの1018分の1もあるはずがないです。
これのせいで面白い記事なのに、全く意味不明の結論になっています。

quintillionは、100京(けい)の単位で、「1018」ではなく、「10の18乗」の意味です。
「手作業によるハッシングの100京倍(10の18乗)の速さ」と訳すのが正しいです。

以下の箇所も同様です。

> ハードウェアの1016分の1です。

原文は「10^16」と書いてあります。この「^」は指数を表し、「10の16乗」の意味です。
正) 「10の16乗」分の1

> 約76×1015倍

原文はここは「67 quadrillion times」となっています。(76ではなく67が正しいようです)
なので、
正) 約67×「10の15乗」
の意味です。

**Comment by FudoHashimoto** [comment]
ご指摘ありがとうございました。
記事を訂正させていただきました。
今後ともPOSTDをよろしくお願いいたします！

**Comment by Masa-Shin** [comment]
>当たりのハッシュは、1.4×1020個のうち1つしかありません。

この箇所がまだ直っていませんでした。原文では10の20乗になっています。

**Comment by FudoHashimoto** [comment]
大変失礼しました。
ご指摘の箇所を修正させていただきました。
