### ISSUE TITLE
[翻訳フィードバック] PythonとKerasを使ってAlphaZero AIを自作する

### ISSUE THREAD

**Issue by furuuchitakahiro** [postdcc/feedback#63]
### 記事タイトル or URL

https://postd.cc/applied-data-sciencehow-to-build-your-own-alphazero-ai-using-python-and-keras/

### フィードバック内容

「2916年3月、Deepmindの...」となっていますが「2016年3月、Deepmindの...」ですかね？

**Comment by siminzhuo** [comment]
ご指摘ありがとうございました。
記事を訂正させていただきました。
今後ともPOSTDをよろしくお願いいたします！
