### ISSUE TITLE
[翻訳フィードバック] バージョンの充足可能性問題

### ISSUE THREAD

**Issue by cia-rana** [postdcc/feedback#64]
### 記事タイトル or URL
バージョンの充足可能性問題
https://postd.cc/version-sat/

### フィードバック内容

長くなるので細かく分けてコメントします。~~一部レビューしきれていないところがあるため、適宜追記していく予定です。~~ 一通りレビューしましたので修正（or 現状維持）をよろしくお願いします。

**Comment by cia-rana** [comment]
> 原文: Dependency hell is NP-complete. But maybe we can climb out.
> 邦訳: Dependency HellとはNP完全のことですが、この状態から脱することができるかもしれません。

この訳だと「Dependency Hell = NP完全」というニュアンスにとらえられてしまいます。なので本来の「Dependency Hell ⊂ NP完全」というニュアンスにするために、
`Dependency HellはNP完全ですが、この状況から脱却できるかもしれません。`
と訳すほうが自然です。

**Comment by cia-rana** [comment]
> 原文: The package version selection problem is to find a set of dependencies that can be used to build a top-level package P that is complete (all dependencies satisfied) and compatible (no two incompatible packages are selected).
> 邦訳: パッケージにおけるバージョン選択の問題は、完全である（全ての依存関係を満たしている）かつ互換性のある（2つの非互換性のパッケージが選択されていない）トップレベルパッケージPをビルドするのに使うことができる依存関係のセットを見つけることです。

`パッケージにおけるバージョン選択の問題とは、完全である（全ての依存関係を満たしている）かつ互換性のある（互換性のない2つのパッケージが選択されていない）トップレベルパッケージPをビルドするために使われる依存関係の集合を見つけることです。`
と訳すほうが自然です。
また以降の「set」も、「集合」または「組」と訳した方が自然な訳になります。

**Comment by cia-rana** [comment]
> 原文: existing package managers
> 邦訳: 既存のパッケージ管理

`既存のパッケージ管理システム`
に修正（表記ゆれのため）。以降も "package manager" の表記ゆれがあるので適宜修正しましょう。

**Comment by cia-rana** [comment]
> 原文: an NP-complete task
> 邦訳: NP完全のタスク

`NP完全なタスク`
に修正。

**Comment by cia-rana** [comment]
> 原文: quadratic in the input
> 邦訳: 入力内の二次式

`入力の二乗`
に修正。ここでは計算量のことを言ってますので。

**Comment by cia-rana** [comment]
> 原文: probably linear, depending on details of the computing model
> 邦訳: 計算モデルの詳細により、一次式の可能性もあります

`計算モデルの詳細によっては、線形かもしれません`
に修正。

**Comment by cia-rana** [comment]
> 原文: A problem is NP-hard if an efficient solution for that problem can be adapted into an efficient solution to every other problem in NP.
> 邦訳: ある問題に対する有効な解決策が、NPに属する全ての他の問題に対する有効な解決策に適合することができる場合、問題はNP困難となります。

`ある問題に対する有効な解決策が、NPに属する他の全ての問題に対する有効な解決策に適合できる場合、問題はNP困難となります。`
に修正。

**Comment by cia-rana** [comment]
> 原文: That's a pretty tall order, but it is enough for us to show how to adapt an efficient solution for VERSION into an efficient solution for one other NP-hard problem (call it HARD) and then rely on the fact that someone else has proven that an efficient solution for HARD can be adapted into an efficient solution for every other problem in NP.
> 邦訳: これは非常に難しい注文ではありますが、VERSIONにおける有効な解決策を、もう1つのNP困難の問題（HARDと呼びます）における有効な解決策に適応させることを証明するだけで十分です。そして、他の誰かが証明したHARDにおける有効な解決策が、NPに属するその他全ての問題における有効な解決策に適応できるという事実に依存すればいいのです。

`これは非常に難しい注文ではありますが、VERSIONに対する有効な解決策を、もう1つのNP困難の問題（HARDと呼びます）に対する有効な解決策に適合させることを証明するだけで十分です。そして、他の誰かが証明したHARDに対する有効な解決策が、NPに属する他の全ての問題に対する有効な解決策に適合できるという事実に依存すればいいのです。`
に修正（表記ゆれのため）。

**Comment by cia-rana** [comment]
> 原文: 3-SAT
> 邦訳: 充足可能性問題

3-SAT は充足可能性問題の一種であり、充足可能性問題そのものではありません。
ですので、3-SAT は 3-SAT のままで訳して大丈夫です。
わかりやすさ優先で「充足可能性問題」と訳したのかと思いましたが、後の方で "satisfiability" を「充足可能性」と訳しているので3-SATにしましょう。

**Comment by cia-rana** [comment]
> 原文: If we extend it to add one more clause,
> 邦訳: 以下のように、項をもう1つ追加した場合はどうでしょうか。

"clause" は論理学の世界では「項」ではなく「節」と訳します。以降の文でも同様です。

**Comment by cia-rana** [comment]
> 原文: The general form of a 3-SAT instance is a formula F that is the conjunction of clauses C1 through Cn over variables V1 through Vm, where each Ci is a disjunction of three literals, each of the form xj or ¬ xj for some variable xj .
> 邦訳: 充足可能性問題のインスタンスにおける一般的な形式は、変数V1からVm,に対する項C1からCnの論理積で、各Ciは3つのリテラル、各xjまたは、いくつかの変数xjにおける¬ xjの論理和である方程式Fとなります。

一文ではわかりにくいので二つ分けましょう。

`3-SATのインスタンスの一般的な形式は、変数V1からVmに対する節C1からCnの論理積から成る方程式Fです。ここで各Ciは3つのリテラルの論理和で、それぞれのリテラルは変数xjを用いてxjまたは¬ xjの形式をとります。`

Vmの後のカンマは除きました。また、V1やVmなどはMathJaxなどが使えましたら数式で表しましょう。

**Comment by cia-rana** [comment]
> 原文: A package can list zero or more packages or specific package versions as dependencies.
> 邦訳: パッケージは0個以上のパッケージまたは特定のパッケージのバージョンを依存関係としてリストすることができる。

`パッケージは0個以上のパッケージのバージョンまたは特定のパッケージのバージョンを依存関係としてリストすることができる。`
に修正。

**Comment by cia-rana** [comment]
> 原文: Given a 3-SAT formula, we can create a package F representing the whole formula, packages C1, C2, ..., Cn representing each clause, and packages X1, X2, ..., Xm representing each variable.
> 邦訳: 充足可能性問題の方程式が与えられれば、パッケージFを作成することができます。このFは、パッケージC1、C2、Cnといった全体の方程式を表しており、Cnは各項を、パッケージX1、X2、Xmなどは各変数を表しています。

`3-SATの方程式が与えられれば、パッケージFを作成することができます。このFは方程式全体、パケージC1, C2, ..., Cnはそれぞれ項を、パッケージX1, X2, ..., Xmは各変数を表しています。`
に修正。

**Comment by cia-rana** [comment]
> 原文: then a satisfying assignment for the original formula
> 邦訳: 元々の方程式における満足する代入は

`元々の方程式を満たす代入は`
に修正。

**Comment by cia-rana** [comment]
> 原文: Xj:1 for each variable xj
> 邦訳: 各変数xjに対するXj

`各変数xjに対するXj:1`
に修正。

**Comment by cia-rana** [comment]
> 原文: a corresponding VERSION instance
> 邦訳: 一致するVERSIONのインスタンス

`対応するVERSIONのインスタンス`
に修正。

**Comment by cia-rana** [comment]
> 原文: The assumptions above are quite minimal
> 邦訳: 上記はかなり最低限の場合を想定しています

`上記はかなり最低限の場合を仮定しています`
に修正。"assumption" の訳が「仮定」と「想定」で表記ゆれしているので「仮定」にそろえましょう。

**Comment by cia-rana** [comment]
> [WIP]
> The assumptions above are quite minimal: packages have a list of dependencies, a package's dependencies can change with its own version to version, a package's dependencies can be restricted to specific versions of those dependencies, and it is possible for two versions of a package to conflict with each other. That may be the bare minimum for a package manager to be useful. Some package managers might not allow a dependency to list a specific version, instead requiring a range, but we can easily change the version requirements 0 and 1 to ≤ 0 and ≥ 1. Some package managers might not assume that different versions of a package conflict by default, but it must be at least possible to specify such a conflict: there can't be two /bin/bash on a Unix system, or two definitions of printf built into a C program.

**Comment by cia-rana** [comment]
> 原文: The assumptions are true of every package manager I have looked at
> 邦訳: 仮定は、調べた全てのパッケージ管理システムにおいて真です

`仮定は、調べた全てのパッケージ管理システムに当てはまります`
に修正。

**Comment by cia-rana** [comment]
> 原文: and more
> 邦訳: またその他複数です

`などなど`
に修正。

**Comment by cia-rana** [comment]
> 原文: The implication is that these package managers faces an NP-complete task.
> 邦訳: どうやらパッケージ管理の実装で直面するのは、NP完全のタスクのようです。

`つまりこれらのパッケージ管理システムは、NP完全なタスクに直面していることを意味します。`
に修正（The implication is that ～: その意味は～である）。

**Comment by cia-rana** [comment]
> 原文: Each must choose between possibly taking a very long time to decide on an installation strategy or possibly reporting an installable package as uninstallable
> 邦訳: インストールの方法を決めるために長い時間を要する可能性があるのか、それともインストールできないものとしてインストール可能なパッケージのレポートするのかを、それぞれが選択しなくてはなりません

`インストール方法を決めるために長い時間を要する可能性があるのか、それともインストールできないものとしてインストール可能なパッケージを報告する可能性があるのか、それぞれのパッケージ管理システムは選択しなければなりません`
に修正。

**Comment by cia-rana** [comment]
> 邦訳: KnuthはThe Art of Computer Programming Volume 4, Fascicle 6で以下のように記述しています。

この次の段落は引用文であることが分かるようにしましょう。

**Comment by cia-rana** [comment]
> 原文: such problems were regarded as hopeless
> 邦訳: このような問題は数年前まで不可能と考えられていましたが

`このような問題は数年前まで対処するのが不可能と考えられていましたが`
に修正（言葉を補足した）。

**Comment by cia-rana** [comment]
> 原文: uses the dep-selector Ruby bindings for the Gecode constraint solver
> 邦訳: Gecodeの制約ソルバのためのRubyバインディングのdep-selectgorを使っています

`Gecodeの制約ソルバとしてRubyバインディングのdep-selectgorを使っています`
に修正。

**Comment by cia-rana** [comment]
> 原文: backtracking solver
> 邦訳: バックトラッキングのソルバ

`バックトラッキングソルバ`
に修正。「の」があると「バックトラッキングのためのソルバ」というニュアンスになる。本来は「バックトラッキングをするソルバ」というニュアンスなので「の」を削除した。

**Comment by cia-rana** [comment]
> 原文: The Debian Quality Assurance team also
> 邦訳: Debianの品質保証チームは

`Debianの品質保証チームも`
に修正。

**Comment by cia-rana** [comment]
> 原文: to manage installation of its plugins
> 邦訳: プラグインの実装を管理するために

`プラグインのインストール状況を管理するために`
に修正。

**Comment by cia-rana** [comment]
> 原文: It also allows multiple versions of a crate to be linked into the final binary.
> 邦訳: これは、複数のバージョンが最終的なバイナリにリンクされることを許可します。

`これにより複数のバージョンが最終的なバイナリにリンクされます。`
に修正。

**Comment by cia-rana** [comment]
> 原文: SAT solvers are as good as they are
> 邦訳: SATソルバが有能であること

`SATソルバが優れていること`
に修正。

**Comment by cia-rana** [comment]
> 原文: systematic testing
> 邦訳: 統計的テスト

`体系的テスト`
に修正。

**Comment by cia-rana** [comment]
> 原文: If a search finds a conflict-free combination, why should we believe the combination will work?
> 邦訳: もし、探索で競合しない組み合わせを見つけた場合、組み合わせが機能するとなぜ信じることができるのでしょう？

`もし探索で競合しない組み合わせを見つけたとして、その組み合わせが機能するとなぜ信じることができるのでしょうか？`
に修正。

**Comment by cia-rana** [comment]
> 原文: Software is hard enough to get right without admitting NP-complete problems into our software configuration decisions. 
> 邦訳: NP完全を自らのソフトウェアのコンフィギュレーションの決定に受け入れることをせずに、ソフトウェアをきちんと理解するのは非常に難しいものです。

`ソフトウェアのコンフィギュレーションの決定にNP完全な問題を介入させずにソフトウェアをきちんと理解するのは非常に難しいものです。`
に修正。

**Comment by cia-rana** [comment]
> 原文: instead is like documenting a bug instead of fixing it.
> 邦訳: 問題を修正せずにバグを添付しているようなものです。

`問題を修正せずにバグを付加しているようなものです。`
に修正。

**Comment by cia-rana** [comment]
> 原文: Another way to avoid NP-completeness
> 邦訳: NP完全性を回避するもう1つの方法

`NP完全性を回避する別の方法`
に修正。"another" は「もう1つ」ではありません。"the other" がそれにあたります。

**Comment by cia-rana** [comment]
> 原文: find a combination of packages
> 邦訳: パッケージの組み合わせを見つける

`パッケージの組み合わせを探す`
に修正。「探索アルゴリズム」に対応してこちらの訳のほうが適切かと思います。

**Comment by cia-rana** [comment]
> 原文: fully-qualified names
> 邦訳: 完全修飾

`完全修飾名`
に修正。

**Comment by cia-rana** [comment]
> 原文: developers are likely not thinking about the entire space of all possible package combinations
> 邦訳: 全ての考え得るパッケージの組み合わせ全体について考えていない可能性があるということです

`考えられる全てのパッケージの組み合わせ全体について考えきれていない可能性があるということです`
に修正。こちらの方が意味が通りやすいかと思われます。

**Comment by cia-rana** [comment]
> 原文: It would help for the developers and their tools to agree about how software is built.
> 邦訳: この考えは、ソフトウェアがどのようにビルドされているかについて開発者とそのツールの整合性を保つために、重要です。

`この考え方は、ソフトウェアのビルド方法について開発者とツールが整合性を保つ際に役立ちます。`
に修正。

**Comment by cia-rana** [comment]
> 原文: If any of these approaches can be made to work in practice
> 邦訳: これらのアプローチのいずれかが、実際に実行されるようになれば

`これらのアプローチのいずれかを実際に実行させることができれば`
に修正。

**Comment by cia-rana** [comment]
> 原文: it could go a long way toward simplifying the operation and understandability of language package managers
> 邦訳: 言語のパッケージ管理の動作と理解性の簡素化に大いに効果があるでしょう

`言語のパッケージ管理の操作性と理解性を大いに簡素化できるでしょう`
に修正。「操作性」は "operability" ですが、訳のしやすさを考えてあえて変えました。

**Comment by cia-rana** [comment]
> [WIP]
> Related Work

**Comment by cia-rana** [comment]
> 原文: using “provides” directives (in RedHat)
> 邦訳: “provides” 名令（RedHatの場合）を用いて

"directive" は「ディレクティブ」とそのまま訳して良いです。
ちなみにディレクティブは「指示子」のことで「名令（命令のこと？）」とはまた意味が違います。

**Comment by cia-rana** [comment]
> 原文: For example, these systems allow a pseudo-package text-editor to be defined that is considered installed when any of the real packages ed, vi, or acme is installed. 
> 邦訳: 例えば、これらのシステムでは、実際のパッケージ、edやvi、acmeのいずれかがインストールされる際に、pseudo-packageのtext-editorがインストール済とみなされる、と定義することができます。

`例えばこれらのシステムでは、実際のパッケージである ed や vi、acme のいずれかがインストールされていれば、擬似パッケージである text-editor がインストールされていると考えるのは明らかです。`
に修正。

**Comment by cia-rana** [comment]
> 原文: I've been unable to find prior written proofs of that fact
> 邦訳: その事実が以前に証明された書面を見つけることはできていません

`その事実が事前に証明されていたとする書面を見つけることはできていません`
に修正。

**Comment by cia-rana** [comment]
> 原文: the underlying problem is still NP-complete
> 邦訳: 根本的な問題は、やはりNP完全です

`根本的な問題は、なおもNP完全であるということです`
に修正。

**Comment by cia-rana** [comment]
> 原文:  Roberto Di Cosmo has written a number of followups to the EDOS report, listed here, in particular, “Dependency solving: a separate concern in component evolution management,” which contains an updated proof. That line of research applies SAT solvers but also works to take user preferences into account.
> Another related line of work is “OPIUM: Optimal Package Install/Uninstall Manager” by Tucker et al., ICSE 2007. OPIUM was the starting point for 0install's solver. 
> 
> 邦訳: Roberto Di Cosmoは、EDOS報告書に続くものをたくさん書いています。こちらがそのリストです。特に、依存関係の解法、コンポーネントの進化するマネジメントでの個別の懸念には、最新版の証明が含まれています。その一連の研究はSATソルバに適用するだけでなく、ユーザプリファレンスを考慮に入れて動作します。
> また別の関連著書には、2007年ICSEで発表されたTuckerらの
OPIUM、最適なパッケージのインストール／アンインストール管理、があります。OPIUMは0installソルバの出発点です。

ここのダブルクオートでくくられている部分が邦訳ではかぎ括弧でくくられていないのはどうしてでしょうか。（後の文で出てくるDaniel Burrowsの論文のタイトルは、邦訳ではかぎ括弧でくくられているのでどちらかに統一しましょう。）

**Comment by cia-rana** [comment]
> 原文: a package's dependencies can be restricted to specific versions of those dependencies, and it is possible for two versions of a package to conflict with each other.
> 邦訳: パッケージの依存関係は特定の依存関係のバージョンを制限し、2つのパッケージのバージョンをお互いに競合関係にすることが可能。

後半の文の主語が「パッケージの依存関係」になっています。ですので、
`パッケージの依存関係は特定の依存関係のバージョンを制限可能。2つのパッケージのバージョンはお互いに競合しうる。`
と訳すほうが適切です。

it is A for B to C
B にとって C することは A だ

**Comment by cia-rana** [comment]
伝え方が悪くて申し訳ありませんが、引用する文は次の画像の通りです。

![image](https://user-images.githubusercontent.com/28956664/38426332-6090491a-39f1-11e8-8ef5-243d7f4653f8.png)

**Comment by siminzhuo** [comment]
沢山丁寧なフィードバックありがとうございます。
ご指摘のとおりでしたので、修正させていただきました！
今後ともPOSTDをよろしくお願いいたします。
