### ISSUE TITLE
[翻訳フィードバック] JavaScript モジュールの現状

### ISSUE THREAD

**Issue by naqtn** [postdcc/feedback#66]
### 記事タイトル or URL
https://postd.cc/the-state-of-javascript-modules/

### フィードバック内容
原文
> Hence, a synchronous require() of an ESM will not be possible.

訳文
> そのため、ESMの非同期require()は不可能となります。

「a」と「synchronous」の間にはスペースが入っており、ここは「非同期」ではなく「同期」が正しいのではないでしょうか。「全て非同期になる」という文脈なので不可能になるのは「同期」かと思います。

**Comment by re-fort** [comment]
フィードバックありがとうございます！
ご指摘のとおりでしたので、記述を修正させていただきました。
今後ともPOSTDをよろしくお願いいたします。
