### ISSUE TITLE
[翻訳フィードバック] モノリシックなRubyからGoによるマイクロサービスへ

### ISSUE THREAD

**Issue by cia-rana** [postdcc/feedback#67]
### 記事タイトル or URL

モノリシックなRubyからGoによるマイクロサービスへ
https://postd.cc/from-a-ruby-monolith-to-microservices-in-go/

### フィードバック内容

画像のリンクが一部切れているため修正をお願いします。
一応画像は
https://web.archive.org/web/20150317213850/https://sourcegraph.com/blog/live/gopherconindia/112656568167
にアーカイブされています。

**Comment by siminzhuo** [comment]
フィードバックありがとうございます。
ご指摘のとおりでしたので、修正させていただきました！
今後ともPOSTDをよろしくお願いいたします。
