### ISSUE TITLE
[翻訳フィードバック] ディープラーニングの限界

### ISSUE THREAD

**Issue by knzm** [postdcc/feedback#68]
### 記事タイトル or URL

https://postd.cc/the-limitations-of-deep-learning/

### フィードバック内容

「局所的一般化　対 極度の一般化」第３段落の「監視付きの学習」は原文だと supervised learning で「教師あり学習」が正しい訳語です。

**Comment by FudoHashimoto** [comment]
フィードバックありがとうございます。
ご指摘のとおりでしたので、修正させていただきました！
今後ともPOSTDをよろしくお願いいたします。
