### ISSUE TITLE
[翻訳フィードバック] 2015年の最優先事項は関数型プログラミング！

### ISSUE THREAD

**Issue by 7cc** [postdcc/feedback#69]
### 記事タイトル or URL
https://postd.cc/functional-programming-should-be-your-1-priority-for-2015/

### フィードバック内容
元の著者がユーザーネームを変更したため、埋め込みのgistが読み込まれません。

**Comment by siminzhuo** [comment]
フィードバックありがとうございます。
ご指摘のとおりでしたので、修正させていただきました！
今後ともPOSTDをよろしくお願いいたします。
