### ISSUE TITLE
[翻訳フィードバック] バージョンの充足可能性問題 (バージョン選択問題の説明文中の「または」は「かつ」ではないか）

### ISSUE THREAD

**Issue by pocket7878** [postdcc/feedback#7]
冒頭の
```
パッケージにおけるバージョン選択の問題は、完全である（全ての依存関係を満たしている）または互換性のある（2つの非互換性のパッケージが選択されていない）トップレベルパッケージPをビルドするのに使うことができる依存関係のセットを見つけることです。
```
ですが、完全である〜と互換性のある〜のつなぎの「または」はORではなく、完全で、かつ互換性のあるセットを見つけることが目的なので、「かつ」ではないでしょうか。

**Comment by mk2** [comment]
頂きましたご指摘を確認し、再度翻訳を検討し修正いたしました。
http://postd.cc/version-sat/

翻訳への的確なフィードバックをしていただき、また別件のご指摘もいただき大変感謝しております。
今後ともPOSTDをどうぞよろしくお願いいたします。
