### ISSUE TITLE
[翻訳フィードバック] Redux-Observable Epic vs Redux-Saga: 何が問題なのか

### ISSUE THREAD

**Issue by terrierscript** [postdcc/feedback#70]
### 記事タイトル or URL
Redux-Observable Epic vs Redux-Saga: 何が問題なのか
### フィードバック内容

> 注釈：
> この演算子は一般に、mergeMに対する安全なデフォルトと考えられます。

こちら、原文から読み取れませんでしたが`mergeMap`のtypoでしょうか？

**Comment by KimDoyun00** [comment]
今回のフィードバックありがとうございます。
mergeMはmergeMapに修正致しました。
