### ISSUE TITLE
[翻訳フィードバック] カオステストでHTTP/2の問題を見つけ出す

### ISSUE THREAD

**Issue by mkamakura** [postdcc/feedback#74]
### 記事タイトル or URL
https://postd.cc/http2-issues/

### フィードバック内容
`HTTP/2テスト結果の解釈`の章にある`ヘッドオブファインブロッキング`は `ヘッドオブラインブロッキング`の誤字かと思われます。

**Comment by siminzhuo** [comment]
フィードバックありがとうございます。
ご指摘のとおりでしたので、修正させていただきました！
今後ともPOSTDをよろしくお願いいたします。
