### ISSUE TITLE
[翻訳フィードバック] 恐竜に教える現代のCSS - Part 1

### ISSUE THREAD

**Issue by krymtkts** [postdcc/feedback#75]
### 記事タイトル or URL

[恐竜に教える現代のCSS – Part 1](https://postd.cc/actualize-networkmodern-css-explained-for-dinosaurs/)

### フィードバック内容

「グリッドベースのレイアウト」の章において、コード`<div class="container">`の欠落があります。

> この例では、flexboxベースレイアウトで追加する必要のあった`
> 
> `が不要なことに注目してください。元のHTMLを変更せずにそのまま使えるのです。CSSは以下のようになります。

原文では次の通りです。

>Note that for this example, we can get rid of the `<div class="container">` that we had to add for the flexbox-based layout — we can simply use the original HTML without modification. Here’s what the CSS looks like:

**Comment by FudoHashimoto** [comment]
フィードバックありがとうございます。
ご指摘のとおりでしたので、修正させていただきました。
今後ともPOSTDをよろしくお願いいたします！
