### ISSUE TITLE
[翻訳フィードバック] Webサイト開発にCSS in JavaScriptを使うのはやめよう

### ISSUE THREAD

**Issue by ysgk** [postdcc/feedback#76]
### 記事タイトル or URL
[Webサイト開発にCSS in JavaScriptを使うのはやめよう | POSTD](https://postd.cc/stop-using-css-in-javascript-for-web-development-fa/)

### フィードバック内容
神話6の「どのコンポーネントも、簡単なボタンではなくロングスクロールになりがちです。」の部分は原文では
> it makes for a long-scroll on any component thats not a simple button.

ですので、「簡単なボタンを除けばどんなコンポーネントも」の意味ですね。

**Comment by FudoHashimoto** [comment]
フィードバックありがとうございます。
ご指摘のとおりでしたので、修正させていただきました。
今後ともPOSTDをよろしくお願いいたします！
