### ISSUE TITLE
[翻訳フィードバック] Pythonのディープラーニングを使い、iPhone XにFace IDを実装した方法

### ISSUE THREAD

**Issue by pocket7878** [postdcc/feedback#77]
### 記事タイトル or URL

Pythonのディープラーニングを使い、iPhone XにFace IDを実装した方法

### フィードバック内容

タイトルの

```
Pythonのディープラーニングを使い、iPhone XにFace IDを実装した方法
```
というのは、`iPhone*に*FaceID`という表現を用いてしまうと、iPhoneX上で動作する
ソフトウェアが最終的な成果物のように読めてしまいますが、原文上では

```
how I implemented a FaceID-like algorithm using Keras
```

のように`FaceID-like`ですし、`some final experiments, done using a Kinect`ですので

```
iPhone XのFace IDを、Pythonとディープラーニングで再現した方法
```

のような方向性のタイトルが良いかもしれません。
（「再現した方法」、とするか「再現する」とするか、「模倣する」とする等の細かい判断は必要だと思います）

**Comment by kimdoyun** [comment]
フィードバックありがとうございます。
タイトルの修正をさせていただきました。
今後ともPOSTDをよろしくお願いいたします！
