### ISSUE TITLE
[翻訳フィードバック] GitトラブルをGetしてしまったら：バージョン管理のお話

### ISSUE THREAD

**Issue by mom0tomo** [postdcc/feedback#78]
### 記事タイトル or URL
https://postd.cc/when-you-git-in-trouble-a-version-control-story/

### フィードバック内容
「彼女のウインク」のところのリンクが壊れています。
下記のように、リンクが重複して貼られているようです。

https://postd.cc/when-you-git-in-trouble-a-version-control-story/%E3%82%92https://www.youtube.com/watch?v=-Zb1lZgN9OE

**Comment by FudoHashimoto** [comment]
フィードバックありがとうございます。
たしかにリンクが壊れていましたので、修正させていただきました。
今後ともPOSTDをよろしくお願いいたします！
