### ISSUE TITLE
[翻訳フィードバック] GitトラブルをGetしてしまったら：バージョン管理のお話

### ISSUE THREAD

**Issue by bellbind** [postdcc/feedback#79]
### 記事タイトル or URL

GitトラブルをGetしてしまったら：バージョン管理のお話

- https://postd.cc/when-you-git-in-trouble-a-version-control-story/

### フィードバック内容

> BLOBオブジェクトは暗号化でハッシュされています。つまり、それぞれのファイルを表すデータのBLOBなのです。

原文では

>  Blob objects are cryptographically-hashed, well, blobs of your data, each representing one of your files. 

"cryptographically-hashed"は「暗号学的ハッシュ化」でしょうか。

この「暗号学的」というのは、衝突不可能性や(似たデータからの)逆算が難しい性質を持っていることです(逆に言うと、ハッシュテーブルや探索アルゴリズムで使うようなハッシュ関数では、そういう性質を持たない簡単なものを使う)。暗号化はしません。

- https://ja.wikipedia.org/wiki/%E6%9A%97%E5%8F%B7%E5%AD%A6%E7%9A%84%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5%E9%96%A2%E6%95%B0
- https://en.wikipedia.org/wiki/Cryptographic_hash_function

---

余談ですが、「BLOBオブジェクト、ツリーオブジェクト、コミットオブジェクト」と訳されてますが、原文の方では、git objectのtype別のデータ構造として、blob型オブジェクト、tree型オブジェクト、commit型オブジェクト、のようなクラス名的な意図で用いているように見えます。

こう考えれば、続く記述の"blob of your data"のように、一般的な個々のファイルデータのBLOB(binary large object)のことだ、と描写したのではないでしょうか。つづくtree objectsやcommit objectsの描写もコミットといったgitコマンド利用側からの概念ではない、そのデータ構造で保持する内容への軽い説明になっています。

**Comment by KimDoyun00** [comment]
翻訳フィードバックありがとうございます。
指摘してもらったcryptographically-hashedは原文リンクでも暗号化方式を説明しており、単語の意味（暗号学的ハッシュ化）ではなくhash化そのままの意味で使われています。
今後ともPOSTDをよろしくお願いいたします！
