### ISSUE TITLE
[翻訳フィードバック] 8つのDocker開発パターン

### ISSUE THREAD

**Issue by eiryu** [postdcc/feedback#8]
名前の掲載OKです。

### typo

1. 共有ベースコンテナ

× 基本的な設定をベースコンテへ
○ 基本的な設定をベースコンテナへ

3. 開発ツールコンテナ

× `ROM`
○ `FROM`

### format

一部Dockerfileの`FROM`の前に半角スペース4文字ではなく全角スペース？2文字が入っている

**Comment by remore** [comment]
翻訳へのtypoとDockerfile不備のフィードバックありがとうございます。
また、返信が遅くなり失礼いたしました。

頂きましたご指摘を確認し、サイト上へ反映させて頂きました。
http://postd.cc/eight-docker-development-patterns/

今後ともPOSTDをどうぞよろしくお願いいたします。
