### ISSUE TITLE
[翻訳フィードバック] GitトラブルをGetしてしまったら：バージョン管理のお話

### ISSUE THREAD

**Issue by sawa0xD** [postdcc/feedback#80]
### 記事タイトル or URL
https://postd.cc/when-you-git-in-trouble-a-version-control-story/

### フィードバック内容
「だからこそ、git参照ドキュメントを読むことになり、git-fsckコマンドの葉間に至ったのです。」
ここは
git参照ドキュメント → gitのリファレンス
葉間 → 発見
ではないでしょうか。
技術資料の場合はreferenceは仕様書という意味合いですので。

原文
"entailed for me a trip to the git reference documentation, where I discovered the git-fsck command"

**Comment by KimDoyun00** [comment]
フィードバックありがとうございます。
指摘された通りだったので修正させていただきました。
今後ともPOSTDをよろしくお願いいたします。
