### ISSUE TITLE
[翻訳フィードバック] Pythonの新しい文字列フォーマット : %記号、str.format()から文字列補間へ

### ISSUE THREAD

**Issue by n-oshiro** [postdcc/feedback#81]
### 記事タイトル or URL
https://postd.cc/new-string-formatting-in-python/

### フィードバック内容
「文字列の補間」の「補間」は「補完」ではないでしょうか。

**Comment by FudoHashimoto** [comment]
フィードバックありがとうございます。
ご指摘の頂いた通り、記事内の意味としては補完が正しいと思いますので修正し反映いたしました。
今後ともPOSTDをよろしくお願いいたします！
