### ISSUE TITLE
[翻訳フィードバック] Linux Insides : カーネル起動プロセス part2

### ISSUE THREAD

**Issue by tohutohu** [postdcc/feedback#82]
### 記事タイトル or URL
[Linux Insides : カーネル起動プロセス part2 | POSTD](https://postd.cc/linux-bootstrap-2/)

### フィードバック内容
元記事
> The 20-bit address bus was replaced with a 32-bit address bus. It allowed access to 4 Gigabytes of memory vs the 1 Megabyte in real mode.

翻訳記事
> アドレスバスが20ビットから32ビットに変更されたことで、リアルモードでは1メガバイトのメモリにしかアクセスできなかったのが、4メガバイトのメモリにアクセスが可能になりました。

4メガバイトではなく4ギガバイトではないでしょうか？

**Comment by FudoHashimoto** [comment]
フィードバックありがとうございます。
ご指摘頂いた通りでしたので、修正し反映いたしました。
今後ともPOSTDをよろしくお願いいたします。
