### ISSUE TITLE
[翻訳フィードバック] パフォーマンス分析の方法論23選

### ISSUE THREAD

**Issue by tkhm** [postdcc/feedback#83]
### 記事タイトル or URL
[パフォーマンス分析の方法論23選 | POSTD](https://postd.cc/performance-analysis-methodology/)

### フィードバック内容
原文との表記方法のズレについてで、具体的には次の2点です。

1. アンチパターンメソドロジーとメソドロジーのそれぞれの開始前に題がついていない

    原文では、Anti-Methodologiesと記載の後、1. Blame-Someone-Else Anti-Methodと続き、6つ紹介後Methodologiesという題の後に1. Ad Hoc Checklist Methodとなっています。それらがないため、後続のAd Hoc......等の内容をアンチパターンかと勘違いを起こしてしまいました。

2. アンチパターンメソドロジーの6つめがなくなっている

    原文では、アンチパターンメソドロジーの6つめとしてTraffic Light Anti-Methodが掲載されています。翻訳後はそちらがなくなってしまっているようです。

原題Performance Analysis Methodologyから敢えてパフォーマンス分析の方法論23選、と意訳されているので、著者の方と相談の上そのような構成に変更した、ということであればよいかと思いますが、そうでなければわざわざ23選とつけるのは原著者の記事の内容から見て、意図にズレがあるようにも思いました。

**Comment by FudoHashimoto** [comment]
フィードバックありがとうございます。
翻訳文は公開時の原文を元にしており、著者からの要望がない限り追加文の翻訳は対応しておりません。
ご不便をおかけして申し訳ございませんが宜しくお願い致します。

**Comment by tkhm** [comment]
>翻訳文は公開時の原文を元にしており、著者からの要望がない限り追加文の翻訳は対応しておりません。

そのような方針であれば承知しました。読者にもそのことがわかりやすく伝わるようになるとより良さそうですね。検討いただきましてありがとうございました。
