### ISSUE TITLE
[翻訳フィードバック] GPUでボロノイ図を描画する : WebGLを用いてスムーズに描画できる高速アルゴリズム

### ISSUE THREAD

**Issue by cia-rana** [postdcc/feedback#84]
### 記事タイトル or URL
https://postd.cc/voronoi-diagrams/

### フィードバック内容

論文のタイトル「Jump Flooding in GPU with Applications to Voronoi Diagram and Distance Transform」

の邦訳は

「GPUとアプリケーションを用いたJump Floodingによるボロノイ図と距離変換」

ではなく

「GPUに適したJump Floodingおよびボロノイ図と距離変換への応用」

のほうが良いです。
（本当は邦訳せずに論文タイトルそのままで記載した方がより良いです）

**Comment by KimDoyun00** [comment]
フィードバックありがとうございます。
指摘された通りだったので修正させていただきました。
今後ともPOSTDをよろしくお願いいたします。
