### ISSUE TITLE
[翻訳フィードバック] GPUでボロノイ図を描画する : WebGLを用いてスムーズに描画できる高速アルゴリズム

### ISSUE THREAD

**Issue by cia-rana** [postdcc/feedback#85]
### 記事タイトル or URL

https://postd.cc/voronoi-diagrams/

### フィードバック内容

原文が更新されたようで、邦訳されていない英文がところどころ見受けられるため、追加で邦訳お願いします。

**Comment by KimDoyun00** [comment]
フィードバックありがとうございます。
翻訳文は公開時の原文を元にしており追加文の翻訳は対応しておりません。
ご不便をおかけして申し訳ございませんが宜しくお願い致します。

**Comment by cia-rana** [comment]
承知しました。
