### ISSUE TITLE
[翻訳フィードバック] 分散型システム徹底入門 - Part 1.

### ISSUE THREAD

**Issue by ytakahashi** [postdcc/feedback#86]
### 記事タイトル or URL
[分散型システム徹底入門 – Part 1. | POSTD](https://postd.cc/a-thorough-introduction-to-distributed-systems-3/)

### フィードバック内容

3 つ目の図の注釈について、

>（右下）水平スケーラビリティだと、イニシャルコストが高くなりがち
（左上）水平スケーラビリティだと、あるポイントを超えてから非常に効率的になる

こちら、（左下）と（右下）の間違いかと思います。

**Comment by KimDoyun00** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容が正しいので修正し反映いたしました。
今後ともPOSTDをよろしくお願いいたします。

**Comment by ytakahashi** [comment]
修正後の図の注釈、（左上）となっているようですが・・・

**Comment by KimDoyun00** [comment]
ありがとうございます。
修正の間違いがありましたので再び修正しますた。
ご迷惑おかけて申し訳ございません。
