### ISSUE TITLE
[翻訳フィードバック] 私たちはなぜReactではなくVue.jsを選んだのか

### ISSUE THREAD

**Issue by kachick** [postdcc/feedback#87]
### 記事タイトル or URL

https://postd.cc/why-we-chose-vuejs-over-react/

### フィードバック内容

>ReactはJS界での括弧たる地位を固めました。

`確固たる地位` の意図かなと思いました。

**Comment by KimDoyun00** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容が正しいので修正し反映いたしました。
今後ともPOSTDをよろしくお願いいたします。

**Comment by kachick** [comment]
ありがとうございます！
