### ISSUE TITLE
[翻訳フィードバック] コーディング面接とSnakeゲームに唯一共通すること

### ISSUE THREAD

**Issue by swdr1904** [postdcc/feedback#88]
### 記事タイトル or URL
[コーディング面接とSnakeゲームに唯一共通すること](https://postd.cc/coding-interviews-and-the-snake-game-have-this-one-thing-in-common/)
### フィードバック内容
翻訳ではないですが、記事内に掲載されているコードで`<`が`&lt`, `>`が`&gt`と表示されています。
検討をお願いします。

**Comment by KimDoyun00** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を確認して修正しました。
今後ともPOSTDをよろしくお願いいたします。
