### ISSUE TITLE
[翻訳フィードバック] ReactのHigher Order Components詳解 : 実装の2つのパターンと、親Componentとの比較

### ISSUE THREAD

**Issue by na0x2c6** [postdcc/feedback#89]
### 記事タイトル or URL
https://postd.cc/react-higher-order-components-in-depth/

### フィードバック内容
下記翻訳部分で少し混乱いたしました。
> WrappedComponentインスタンスのpropsを変更したり作成したりすることはできません。これは、React Componentは自身が受け取ったpropsを変更することができませんが、renderメソッドで出力された要素のpropsを変更することはできるからです。

原文:
> You cannot edit or create props of the WrappedComponent instance, because a React Component cannot edit the props it receives, but you can change the props of the elements that are outputted from the render method.

下記のような意味合いかと思うのですが、いかがでしょうか。

React Component は受け取った props を変更することはできないので、WrappedComponent インスタンスの props を変更したり作成したりすることは**できません**が、**render** メソッドによって出力された要素の props は変更することが**できます**。

**Comment by KimDoyun00** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容が正しいので修正し反映いたしました。
今後ともPOSTDをよろしくお願いいたします。
