### ISSUE TITLE
[翻訳フィードバック] 優秀な面接者に共通するものとは？　数千の実例を調べてみました。- 後編

### ISSUE THREAD

**Issue by keng000** [postdcc/feedback#90]
### 記事タイトル or URL
https://postd.cc/what-do-the-best-interviewers-have-in-common-we-looked-at-thousands-of-real-interviews-to-find-out/

### フィードバック

翻訳についてではなく、フォーマット崩れについて。

「質問する」節の2段落目最後、「###高評価」は1文となっていますが本来は見出し分けをする部分でしょうか。Markdownならば、その前に改行を挟んで見出しを働かせる部分では無いかと考えています。

また「>」から始まる引用部分について、Markdownならばそれの後に空白を入れて引用を働かせることで、より記事が見やすくなるのでは無いかと思います。

**Comment by FudoHashimoto** [comment]
フィードバックありがとうございます。
ご指摘頂いたフォーマット崩れについて修正を反映いたしました。
今後ともPOSTDをよろしくお願いいたします。
