### ISSUE TITLE
[翻訳フィードバック] 2017年JavaScriptのテスト概論

### ISSUE THREAD

**Issue by tnzk** [postdcc/feedback#94]
### 記事タイトル or URL

https://postd.cc/a-complete-guide-to-testing-javascript-in-2017/

### フィードバック内容

「まとめ」の末尾に「技術部門」とある部分は、文脈からいって「技術的負債」と思われます。原文中で文脈上 debt となるのが自然なところを dept と typo しているのを忠実に訳しているものと思われますが、意図的でしょうか。

**Comment by KimDoyun00** [comment]
フィードバックありがとうございます。
翻訳の際に意図的に翻訳したと思われますが、
文脈的に技術的負債が正しいので修正致しました。
今後ともPOSTDをよろしくお願いいたします。
