### ISSUE TITLE
[翻訳フィードバック] 分岐予測の簡単な歴史 - Part 1

### ISSUE THREAD

**Issue by HASHIMOTO-Takafumi** [postdcc/feedback#95]
### 記事タイトル or URL

https://postd.cc/branch-prediction-2/

### フィードバック内容

> branch_pct * 1 + non_branch_pct * 20 = 0.2 * 20 + 0.8 * 1 = 4 + 0.8 = 4.8 cycles

という部分について、原文も同じ式になっていますが

> 非分岐はクロック当たり平均1命令、予測しない、または予測を誤った分岐には20サイクルが必要

> 恐らく20％が分岐で、80％がその他の動作といったところでしょう。

という記述と次の式との整合性からして、最左辺は`branch_pct * 20 + non_branch_pct * 1`のように係数を逆にしたものが正しいように思われます。

**Comment by Seiichi-Akiba** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を確認して修正いたしました。
今後ともPOSTDをよろしくお願いいたします。

**Comment by Seiichi-Akiba** [comment]
フィードバックありがとうございます。
ご指摘の件でございますが、POSTDでは記事の原文を主とした翻訳を実施しております。
そのため、原文と変わってしまう表記をする事が出来ないため、申し訳ございませんが現状のままの対応とさせていただきます。
ご指摘をいただいたにも関わらず申し訳ございません。
今後ともPOSTDをよろしくお願いいたします。

**Comment by Hidetomi** [comment]
同じような指摘が出される可能性もあると思います。
注釈を付けるなど原文を崩さない別の方法で修正を表現することは可能ですか？

**Comment by Seiichi-Akiba** [comment]
ご指摘ありがとうございます。
申し訳ございませんが、上記のとおり今回は現状のままの対応とさせていただきます。
よろしくお願いいたします。
