### ISSUE TITLE
[翻訳フィードバック] Bashアプリケーションをテストする

### ISSUE THREAD

**Issue by nwtgck** [postdcc/feedback#98]
いつも素晴らしい記事をありがとうございます

### 記事タイトル or URL
<https://postd.cc/bash%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E3%83%86%E3%82%B9%E3%83%88%E3%81%99%E3%82%8B/>

### フィードバック内容

> 最初に目にとまった選択肢はassert.hという小さなフレームワークでした。

は

「最初に目にとまった選択肢はassert.**sh**という小さなフレームワークでした。」

のタイポかもしれません。

----
対応する原文も
One of the first options that I noticed was a small framework assert.**sh**.
となっていることを確認しました。

**Comment by munehiroochi** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を確認して修正しました。
今後ともPOSTDをよろしくお願いいたします。
