### ISSUE TITLE
[翻訳フィードバック] プログラマの採用面接で聞かれる、データ構造とアルゴリズムに関する50以上の質問

### ISSUE THREAD

**Issue by axjack** [postdcc/feedback#99]
### 記事タイトル or URL
https://postd.cc/50-data-structure-and-algorithms-interview-questions-for-programmers/

### フィードバック内容
`0(1)` は `O(1)`と訂正すべきだと思います。

#### 該当箇所
本文㆗の
```
配列のデータ構造の重要な利点は、インデックスさえ知っていれば高速で0(1)の検索ができることですが、既存の配列のサイズは変更できないため、配列から要素の追加と削除を行う場合は遅くなります。
```
の `0(1)`

は、翻訳元だと

```
The key benefit of an array data structure is that it offers fast O(1) search if you know the index, but adding and removing an element from an array is slow because you cannot change the size of the array once it’s created.
```
の通り`O(1) ` です。オーダー記法のO(オー)であって、0(ゼロ)ではありません。

**Comment by munehiroochi** [comment]
フィードバックありがとうございます。
ご指摘の頂いた内容を確認して修正しました。
今後ともPOSTDをよろしくお願いいたします。
